//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IsNullable=false)]
public partial class nfeProc : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFe nFeField;
    
    private nfeProcProtNFe protNFeField;
    
    private decimal versaoField;
    
    /// <remarks/>
    public nfeProcNFe NFe {
        get {
            return this.nFeField;
        }
        set {
            this.nFeField = value;
            this.RaisePropertyChanged("NFe");
        }
    }
    
    /// <remarks/>
    public nfeProcProtNFe protNFe {
        get {
            return this.protNFeField;
        }
        set {
            this.protNFeField = value;
            this.RaisePropertyChanged("protNFe");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
            this.RaisePropertyChanged("versao");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFe : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFe infNFeField;
    
    private Signature signatureField;
    
    /// <remarks/>
    public nfeProcNFeInfNFe infNFe {
        get {
            return this.infNFeField;
        }
        set {
            this.infNFeField = value;
            this.RaisePropertyChanged("infNFe");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public Signature Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
            this.RaisePropertyChanged("Signature");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFe : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeIde ideField;
    
    private nfeProcNFeInfNFeEmit emitField;
    
    private nfeProcNFeInfNFeDest destField;
    
    private nfeProcNFeInfNFeDet detField;
    
    private nfeProcNFeInfNFeTotal totalField;
    
    private nfeProcNFeInfNFeTransp transpField;
    
    private nfeProcNFeInfNFeCobr cobrField;
    
    private nfeProcNFeInfNFePag pagField;
    
    private nfeProcNFeInfNFeInfAdic infAdicField;
    
    private string idField;
    
    private decimal versaoField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeIde ide {
        get {
            return this.ideField;
        }
        set {
            this.ideField = value;
            this.RaisePropertyChanged("ide");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeEmit emit {
        get {
            return this.emitField;
        }
        set {
            this.emitField = value;
            this.RaisePropertyChanged("emit");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDest dest {
        get {
            return this.destField;
        }
        set {
            this.destField = value;
            this.RaisePropertyChanged("dest");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDet det {
        get {
            return this.detField;
        }
        set {
            this.detField = value;
            this.RaisePropertyChanged("det");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeTotal total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
            this.RaisePropertyChanged("total");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeTransp transp {
        get {
            return this.transpField;
        }
        set {
            this.transpField = value;
            this.RaisePropertyChanged("transp");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeCobr cobr {
        get {
            return this.cobrField;
        }
        set {
            this.cobrField = value;
            this.RaisePropertyChanged("cobr");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFePag pag {
        get {
            return this.pagField;
        }
        set {
            this.pagField = value;
            this.RaisePropertyChanged("pag");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeInfAdic infAdic {
        get {
            return this.infAdicField;
        }
        set {
            this.infAdicField = value;
            this.RaisePropertyChanged("infAdic");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("Id");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
            this.RaisePropertyChanged("versao");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeIde : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte cUFField;
    
    private uint cNFField;
    
    private string natOpField;
    
    private byte modField;
    
    private byte serieField;
    
    private ushort nNFField;
    
    private System.DateTime dhEmiField;
    
    private System.DateTime dhSaiEntField;
    
    private byte tpNFField;
    
    private byte idDestField;
    
    private uint cMunFGField;
    
    private byte tpImpField;
    
    private byte tpEmisField;
    
    private byte cDVField;
    
    private byte tpAmbField;
    
    private byte finNFeField;
    
    private byte indFinalField;
    
    private byte indPresField;
    
    private byte procEmiField;
    
    private decimal verProcField;
    
    private nfeProcNFeInfNFeIdeNFref nFrefField;
    
    /// <remarks/>
    public byte cUF {
        get {
            return this.cUFField;
        }
        set {
            this.cUFField = value;
            this.RaisePropertyChanged("cUF");
        }
    }
    
    /// <remarks/>
    public uint cNF {
        get {
            return this.cNFField;
        }
        set {
            this.cNFField = value;
            this.RaisePropertyChanged("cNF");
        }
    }
    
    /// <remarks/>
    public string natOp {
        get {
            return this.natOpField;
        }
        set {
            this.natOpField = value;
            this.RaisePropertyChanged("natOp");
        }
    }
    
    /// <remarks/>
    public byte mod {
        get {
            return this.modField;
        }
        set {
            this.modField = value;
            this.RaisePropertyChanged("mod");
        }
    }
    
    /// <remarks/>
    public byte serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
            this.RaisePropertyChanged("serie");
        }
    }
    
    /// <remarks/>
    public ushort nNF {
        get {
            return this.nNFField;
        }
        set {
            this.nNFField = value;
            this.RaisePropertyChanged("nNF");
        }
    }
    
    /// <remarks/>
    public System.DateTime dhEmi {
        get {
            return this.dhEmiField;
        }
        set {
            this.dhEmiField = value;
            this.RaisePropertyChanged("dhEmi");
        }
    }
    
    /// <remarks/>
    public System.DateTime dhSaiEnt {
        get {
            return this.dhSaiEntField;
        }
        set {
            this.dhSaiEntField = value;
            this.RaisePropertyChanged("dhSaiEnt");
        }
    }
    
    /// <remarks/>
    public byte tpNF {
        get {
            return this.tpNFField;
        }
        set {
            this.tpNFField = value;
            this.RaisePropertyChanged("tpNF");
        }
    }
    
    /// <remarks/>
    public byte idDest {
        get {
            return this.idDestField;
        }
        set {
            this.idDestField = value;
            this.RaisePropertyChanged("idDest");
        }
    }
    
    /// <remarks/>
    public uint cMunFG {
        get {
            return this.cMunFGField;
        }
        set {
            this.cMunFGField = value;
            this.RaisePropertyChanged("cMunFG");
        }
    }
    
    /// <remarks/>
    public byte tpImp {
        get {
            return this.tpImpField;
        }
        set {
            this.tpImpField = value;
            this.RaisePropertyChanged("tpImp");
        }
    }
    
    /// <remarks/>
    public byte tpEmis {
        get {
            return this.tpEmisField;
        }
        set {
            this.tpEmisField = value;
            this.RaisePropertyChanged("tpEmis");
        }
    }
    
    /// <remarks/>
    public byte cDV {
        get {
            return this.cDVField;
        }
        set {
            this.cDVField = value;
            this.RaisePropertyChanged("cDV");
        }
    }
    
    /// <remarks/>
    public byte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
            this.RaisePropertyChanged("tpAmb");
        }
    }
    
    /// <remarks/>
    public byte finNFe {
        get {
            return this.finNFeField;
        }
        set {
            this.finNFeField = value;
            this.RaisePropertyChanged("finNFe");
        }
    }
    
    /// <remarks/>
    public byte indFinal {
        get {
            return this.indFinalField;
        }
        set {
            this.indFinalField = value;
            this.RaisePropertyChanged("indFinal");
        }
    }
    
    /// <remarks/>
    public byte indPres {
        get {
            return this.indPresField;
        }
        set {
            this.indPresField = value;
            this.RaisePropertyChanged("indPres");
        }
    }
    
    /// <remarks/>
    public byte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
            this.RaisePropertyChanged("procEmi");
        }
    }
    
    /// <remarks/>
    public decimal verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
            this.RaisePropertyChanged("verProc");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeIdeNFref NFref {
        get {
            return this.nFrefField;
        }
        set {
            this.nFrefField = value;
            this.RaisePropertyChanged("NFref");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeIdeNFref : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string refNFeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string refNFe {
        get {
            return this.refNFeField;
        }
        set {
            this.refNFeField = value;
            this.RaisePropertyChanged("refNFe");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeEmit : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ulong cNPJField;
    
    private string xNomeField;
    
    private string xFantField;
    
    private nfeProcNFeInfNFeEmitEnderEmit enderEmitField;
    
    private ulong ieField;
    
    private byte cRTField;
    
    /// <remarks/>
    public ulong CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
            this.RaisePropertyChanged("CNPJ");
        }
    }
    
    /// <remarks/>
    public string xNome {
        get {
            return this.xNomeField;
        }
        set {
            this.xNomeField = value;
            this.RaisePropertyChanged("xNome");
        }
    }
    
    /// <remarks/>
    public string xFant {
        get {
            return this.xFantField;
        }
        set {
            this.xFantField = value;
            this.RaisePropertyChanged("xFant");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeEmitEnderEmit enderEmit {
        get {
            return this.enderEmitField;
        }
        set {
            this.enderEmitField = value;
            this.RaisePropertyChanged("enderEmit");
        }
    }
    
    /// <remarks/>
    public ulong IE {
        get {
            return this.ieField;
        }
        set {
            this.ieField = value;
            this.RaisePropertyChanged("IE");
        }
    }
    
    /// <remarks/>
    public byte CRT {
        get {
            return this.cRTField;
        }
        set {
            this.cRTField = value;
            this.RaisePropertyChanged("CRT");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeEmitEnderEmit : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string xLgrField;
    
    private byte nroField;
    
    private string xCplField;
    
    private string xBairroField;
    
    private uint cMunField;
    
    private string xMunField;
    
    private string ufField;
    
    private uint cEPField;
    
    private ushort cPaisField;
    
    private string xPaisField;
    
    /// <remarks/>
    public string xLgr {
        get {
            return this.xLgrField;
        }
        set {
            this.xLgrField = value;
            this.RaisePropertyChanged("xLgr");
        }
    }
    
    /// <remarks/>
    public byte nro {
        get {
            return this.nroField;
        }
        set {
            this.nroField = value;
            this.RaisePropertyChanged("nro");
        }
    }
    
    /// <remarks/>
    public string xCpl {
        get {
            return this.xCplField;
        }
        set {
            this.xCplField = value;
            this.RaisePropertyChanged("xCpl");
        }
    }
    
    /// <remarks/>
    public string xBairro {
        get {
            return this.xBairroField;
        }
        set {
            this.xBairroField = value;
            this.RaisePropertyChanged("xBairro");
        }
    }
    
    /// <remarks/>
    public uint cMun {
        get {
            return this.cMunField;
        }
        set {
            this.cMunField = value;
            this.RaisePropertyChanged("cMun");
        }
    }
    
    /// <remarks/>
    public string xMun {
        get {
            return this.xMunField;
        }
        set {
            this.xMunField = value;
            this.RaisePropertyChanged("xMun");
        }
    }
    
    /// <remarks/>
    public string UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
            this.RaisePropertyChanged("UF");
        }
    }
    
    /// <remarks/>
    public uint CEP {
        get {
            return this.cEPField;
        }
        set {
            this.cEPField = value;
            this.RaisePropertyChanged("CEP");
        }
    }
    
    /// <remarks/>
    public ushort cPais {
        get {
            return this.cPaisField;
        }
        set {
            this.cPaisField = value;
            this.RaisePropertyChanged("cPais");
        }
    }
    
    /// <remarks/>
    public string xPais {
        get {
            return this.xPaisField;
        }
        set {
            this.xPaisField = value;
            this.RaisePropertyChanged("xPais");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ulong cNPJField;
    
    private string xNomeField;
    
    private nfeProcNFeInfNFeDestEnderDest enderDestField;
    
    private byte indIEDestField;
    
    private string emailField;
    
    /// <remarks/>
    public ulong CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
            this.RaisePropertyChanged("CNPJ");
        }
    }
    
    /// <remarks/>
    public string xNome {
        get {
            return this.xNomeField;
        }
        set {
            this.xNomeField = value;
            this.RaisePropertyChanged("xNome");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDestEnderDest enderDest {
        get {
            return this.enderDestField;
        }
        set {
            this.enderDestField = value;
            this.RaisePropertyChanged("enderDest");
        }
    }
    
    /// <remarks/>
    public byte indIEDest {
        get {
            return this.indIEDestField;
        }
        set {
            this.indIEDestField = value;
            this.RaisePropertyChanged("indIEDest");
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
            this.RaisePropertyChanged("email");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDestEnderDest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string xLgrField;
    
    private byte nroField;
    
    private string xCplField;
    
    private string xBairroField;
    
    private uint cMunField;
    
    private string xMunField;
    
    private string ufField;
    
    private uint cEPField;
    
    private ushort cPaisField;
    
    private string xPaisField;
    
    private uint foneField;
    
    /// <remarks/>
    public string xLgr {
        get {
            return this.xLgrField;
        }
        set {
            this.xLgrField = value;
            this.RaisePropertyChanged("xLgr");
        }
    }
    
    /// <remarks/>
    public byte nro {
        get {
            return this.nroField;
        }
        set {
            this.nroField = value;
            this.RaisePropertyChanged("nro");
        }
    }
    
    /// <remarks/>
    public string xCpl {
        get {
            return this.xCplField;
        }
        set {
            this.xCplField = value;
            this.RaisePropertyChanged("xCpl");
        }
    }
    
    /// <remarks/>
    public string xBairro {
        get {
            return this.xBairroField;
        }
        set {
            this.xBairroField = value;
            this.RaisePropertyChanged("xBairro");
        }
    }
    
    /// <remarks/>
    public uint cMun {
        get {
            return this.cMunField;
        }
        set {
            this.cMunField = value;
            this.RaisePropertyChanged("cMun");
        }
    }
    
    /// <remarks/>
    public string xMun {
        get {
            return this.xMunField;
        }
        set {
            this.xMunField = value;
            this.RaisePropertyChanged("xMun");
        }
    }
    
    /// <remarks/>
    public string UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
            this.RaisePropertyChanged("UF");
        }
    }
    
    /// <remarks/>
    public uint CEP {
        get {
            return this.cEPField;
        }
        set {
            this.cEPField = value;
            this.RaisePropertyChanged("CEP");
        }
    }
    
    /// <remarks/>
    public ushort cPais {
        get {
            return this.cPaisField;
        }
        set {
            this.cPaisField = value;
            this.RaisePropertyChanged("cPais");
        }
    }
    
    /// <remarks/>
    public string xPais {
        get {
            return this.xPaisField;
        }
        set {
            this.xPaisField = value;
            this.RaisePropertyChanged("xPais");
        }
    }
    
    /// <remarks/>
    public uint fone {
        get {
            return this.foneField;
        }
        set {
            this.foneField = value;
            this.RaisePropertyChanged("fone");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDet : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeDetProd prodField;
    
    private nfeProcNFeInfNFeDetImposto impostoField;
    
    private byte nItemField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetProd prod {
        get {
            return this.prodField;
        }
        set {
            this.prodField = value;
            this.RaisePropertyChanged("prod");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImposto imposto {
        get {
            return this.impostoField;
        }
        set {
            this.impostoField = value;
            this.RaisePropertyChanged("imposto");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte nItem {
        get {
            return this.nItemField;
        }
        set {
            this.nItemField = value;
            this.RaisePropertyChanged("nItem");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetProd : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte cProdField;
    
    private string cEANField;
    
    private string xProdField;
    
    private uint nCMField;
    
    private uint cESTField;
    
    private byte eXTIPIField;
    
    private ushort cFOPField;
    
    private string uComField;
    
    private decimal qComField;
    
    private decimal vUnComField;
    
    private decimal vProdField;
    
    private string cEANTribField;
    
    private string uTribField;
    
    private decimal qTribField;
    
    private decimal vUnTribField;
    
    private byte indTotField;
    
    /// <remarks/>
    public byte cProd {
        get {
            return this.cProdField;
        }
        set {
            this.cProdField = value;
            this.RaisePropertyChanged("cProd");
        }
    }
    
    /// <remarks/>
    public string cEAN {
        get {
            return this.cEANField;
        }
        set {
            this.cEANField = value;
            this.RaisePropertyChanged("cEAN");
        }
    }
    
    /// <remarks/>
    public string xProd {
        get {
            return this.xProdField;
        }
        set {
            this.xProdField = value;
            this.RaisePropertyChanged("xProd");
        }
    }
    
    /// <remarks/>
    public uint NCM {
        get {
            return this.nCMField;
        }
        set {
            this.nCMField = value;
            this.RaisePropertyChanged("NCM");
        }
    }
    
    /// <remarks/>
    public uint CEST {
        get {
            return this.cESTField;
        }
        set {
            this.cESTField = value;
            this.RaisePropertyChanged("CEST");
        }
    }
    
    /// <remarks/>
    public byte EXTIPI {
        get {
            return this.eXTIPIField;
        }
        set {
            this.eXTIPIField = value;
            this.RaisePropertyChanged("EXTIPI");
        }
    }
    
    /// <remarks/>
    public ushort CFOP {
        get {
            return this.cFOPField;
        }
        set {
            this.cFOPField = value;
            this.RaisePropertyChanged("CFOP");
        }
    }
    
    /// <remarks/>
    public string uCom {
        get {
            return this.uComField;
        }
        set {
            this.uComField = value;
            this.RaisePropertyChanged("uCom");
        }
    }
    
    /// <remarks/>
    public decimal qCom {
        get {
            return this.qComField;
        }
        set {
            this.qComField = value;
            this.RaisePropertyChanged("qCom");
        }
    }
    
    /// <remarks/>
    public decimal vUnCom {
        get {
            return this.vUnComField;
        }
        set {
            this.vUnComField = value;
            this.RaisePropertyChanged("vUnCom");
        }
    }
    
    /// <remarks/>
    public decimal vProd {
        get {
            return this.vProdField;
        }
        set {
            this.vProdField = value;
            this.RaisePropertyChanged("vProd");
        }
    }
    
    /// <remarks/>
    public string cEANTrib {
        get {
            return this.cEANTribField;
        }
        set {
            this.cEANTribField = value;
            this.RaisePropertyChanged("cEANTrib");
        }
    }
    
    /// <remarks/>
    public string uTrib {
        get {
            return this.uTribField;
        }
        set {
            this.uTribField = value;
            this.RaisePropertyChanged("uTrib");
        }
    }
    
    /// <remarks/>
    public decimal qTrib {
        get {
            return this.qTribField;
        }
        set {
            this.qTribField = value;
            this.RaisePropertyChanged("qTrib");
        }
    }
    
    /// <remarks/>
    public decimal vUnTrib {
        get {
            return this.vUnTribField;
        }
        set {
            this.vUnTribField = value;
            this.RaisePropertyChanged("vUnTrib");
        }
    }
    
    /// <remarks/>
    public byte indTot {
        get {
            return this.indTotField;
        }
        set {
            this.indTotField = value;
            this.RaisePropertyChanged("indTot");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImposto : object, System.ComponentModel.INotifyPropertyChanged {
    
    private decimal vTotTribField;
    
    private nfeProcNFeInfNFeDetImpostoICMS iCMSField;
    
    private nfeProcNFeInfNFeDetImpostoPIS pISField;
    
    private nfeProcNFeInfNFeDetImpostoCOFINS cOFINSField;
    
    /// <remarks/>
    public decimal vTotTrib {
        get {
            return this.vTotTribField;
        }
        set {
            this.vTotTribField = value;
            this.RaisePropertyChanged("vTotTrib");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoICMS ICMS {
        get {
            return this.iCMSField;
        }
        set {
            this.iCMSField = value;
            this.RaisePropertyChanged("ICMS");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoPIS PIS {
        get {
            return this.pISField;
        }
        set {
            this.pISField = value;
            this.RaisePropertyChanged("PIS");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoCOFINS COFINS {
        get {
            return this.cOFINSField;
        }
        set {
            this.cOFINSField = value;
            this.RaisePropertyChanged("COFINS");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoICMS : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeDetImpostoICMSICMS60 iCMS60Field;
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoICMSICMS60 ICMS60 {
        get {
            return this.iCMS60Field;
        }
        set {
            this.iCMS60Field = value;
            this.RaisePropertyChanged("ICMS60");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoICMSICMS60 : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte origField;
    
    private byte cSTField;
    
    private decimal vBCSTRetField;
    
    private decimal pSTField;
    
    private decimal vICMSSTRetField;
    
    /// <remarks/>
    public byte orig {
        get {
            return this.origField;
        }
        set {
            this.origField = value;
            this.RaisePropertyChanged("orig");
        }
    }
    
    /// <remarks/>
    public byte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
            this.RaisePropertyChanged("CST");
        }
    }
    
    /// <remarks/>
    public decimal vBCSTRet {
        get {
            return this.vBCSTRetField;
        }
        set {
            this.vBCSTRetField = value;
            this.RaisePropertyChanged("vBCSTRet");
        }
    }
    
    /// <remarks/>
    public decimal pST {
        get {
            return this.pSTField;
        }
        set {
            this.pSTField = value;
            this.RaisePropertyChanged("pST");
        }
    }
    
    /// <remarks/>
    public decimal vICMSSTRet {
        get {
            return this.vICMSSTRetField;
        }
        set {
            this.vICMSSTRetField = value;
            this.RaisePropertyChanged("vICMSSTRet");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoPIS : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeDetImpostoPISPISAliq pISAliqField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoPISPISAliq PISAliq {
        get {
            return this.pISAliqField;
        }
        set {
            this.pISAliqField = value;
            this.RaisePropertyChanged("PISAliq");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoPISPISAliq : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte cSTField;
    
    private decimal vBCField;
    
    private decimal pPISField;
    
    private decimal vPISField;
    
    /// <remarks/>
    public byte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
            this.RaisePropertyChanged("CST");
        }
    }
    
    /// <remarks/>
    public decimal vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
            this.RaisePropertyChanged("vBC");
        }
    }
    
    /// <remarks/>
    public decimal pPIS {
        get {
            return this.pPISField;
        }
        set {
            this.pPISField = value;
            this.RaisePropertyChanged("pPIS");
        }
    }
    
    /// <remarks/>
    public decimal vPIS {
        get {
            return this.vPISField;
        }
        set {
            this.vPISField = value;
            this.RaisePropertyChanged("vPIS");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoCOFINS : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeDetImpostoCOFINSCOFINSAliq cOFINSAliqField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeDetImpostoCOFINSCOFINSAliq COFINSAliq {
        get {
            return this.cOFINSAliqField;
        }
        set {
            this.cOFINSAliqField = value;
            this.RaisePropertyChanged("COFINSAliq");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeDetImpostoCOFINSCOFINSAliq : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte cSTField;
    
    private decimal vBCField;
    
    private decimal pCOFINSField;
    
    private decimal vCOFINSField;
    
    /// <remarks/>
    public byte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
            this.RaisePropertyChanged("CST");
        }
    }
    
    /// <remarks/>
    public decimal vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
            this.RaisePropertyChanged("vBC");
        }
    }
    
    /// <remarks/>
    public decimal pCOFINS {
        get {
            return this.pCOFINSField;
        }
        set {
            this.pCOFINSField = value;
            this.RaisePropertyChanged("pCOFINS");
        }
    }
    
    /// <remarks/>
    public decimal vCOFINS {
        get {
            return this.vCOFINSField;
        }
        set {
            this.vCOFINSField = value;
            this.RaisePropertyChanged("vCOFINS");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeTotal : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeTotalICMSTot iCMSTotField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeTotalICMSTot ICMSTot {
        get {
            return this.iCMSTotField;
        }
        set {
            this.iCMSTotField = value;
            this.RaisePropertyChanged("ICMSTot");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeTotalICMSTot : object, System.ComponentModel.INotifyPropertyChanged {
    
    private decimal vBCField;
    
    private decimal vICMSField;
    
    private decimal vICMSDesonField;
    
    private decimal vFCPField;
    
    private decimal vBCSTField;
    
    private decimal vSTField;
    
    private decimal vFCPSTField;
    
    private decimal vFCPSTRetField;
    
    private decimal vProdField;
    
    private decimal vFreteField;
    
    private decimal vSegField;
    
    private decimal vDescField;
    
    private decimal vIIField;
    
    private decimal vIPIField;
    
    private decimal vIPIDevolField;
    
    private decimal vPISField;
    
    private decimal vCOFINSField;
    
    private decimal vOutroField;
    
    private decimal vNFField;
    
    private decimal vTotTribField;
    
    /// <remarks/>
    public decimal vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
            this.RaisePropertyChanged("vBC");
        }
    }
    
    /// <remarks/>
    public decimal vICMS {
        get {
            return this.vICMSField;
        }
        set {
            this.vICMSField = value;
            this.RaisePropertyChanged("vICMS");
        }
    }
    
    /// <remarks/>
    public decimal vICMSDeson {
        get {
            return this.vICMSDesonField;
        }
        set {
            this.vICMSDesonField = value;
            this.RaisePropertyChanged("vICMSDeson");
        }
    }
    
    /// <remarks/>
    public decimal vFCP {
        get {
            return this.vFCPField;
        }
        set {
            this.vFCPField = value;
            this.RaisePropertyChanged("vFCP");
        }
    }
    
    /// <remarks/>
    public decimal vBCST {
        get {
            return this.vBCSTField;
        }
        set {
            this.vBCSTField = value;
            this.RaisePropertyChanged("vBCST");
        }
    }
    
    /// <remarks/>
    public decimal vST {
        get {
            return this.vSTField;
        }
        set {
            this.vSTField = value;
            this.RaisePropertyChanged("vST");
        }
    }
    
    /// <remarks/>
    public decimal vFCPST {
        get {
            return this.vFCPSTField;
        }
        set {
            this.vFCPSTField = value;
            this.RaisePropertyChanged("vFCPST");
        }
    }
    
    /// <remarks/>
    public decimal vFCPSTRet {
        get {
            return this.vFCPSTRetField;
        }
        set {
            this.vFCPSTRetField = value;
            this.RaisePropertyChanged("vFCPSTRet");
        }
    }
    
    /// <remarks/>
    public decimal vProd {
        get {
            return this.vProdField;
        }
        set {
            this.vProdField = value;
            this.RaisePropertyChanged("vProd");
        }
    }
    
    /// <remarks/>
    public decimal vFrete {
        get {
            return this.vFreteField;
        }
        set {
            this.vFreteField = value;
            this.RaisePropertyChanged("vFrete");
        }
    }
    
    /// <remarks/>
    public decimal vSeg {
        get {
            return this.vSegField;
        }
        set {
            this.vSegField = value;
            this.RaisePropertyChanged("vSeg");
        }
    }
    
    /// <remarks/>
    public decimal vDesc {
        get {
            return this.vDescField;
        }
        set {
            this.vDescField = value;
            this.RaisePropertyChanged("vDesc");
        }
    }
    
    /// <remarks/>
    public decimal vII {
        get {
            return this.vIIField;
        }
        set {
            this.vIIField = value;
            this.RaisePropertyChanged("vII");
        }
    }
    
    /// <remarks/>
    public decimal vIPI {
        get {
            return this.vIPIField;
        }
        set {
            this.vIPIField = value;
            this.RaisePropertyChanged("vIPI");
        }
    }
    
    /// <remarks/>
    public decimal vIPIDevol {
        get {
            return this.vIPIDevolField;
        }
        set {
            this.vIPIDevolField = value;
            this.RaisePropertyChanged("vIPIDevol");
        }
    }
    
    /// <remarks/>
    public decimal vPIS {
        get {
            return this.vPISField;
        }
        set {
            this.vPISField = value;
            this.RaisePropertyChanged("vPIS");
        }
    }
    
    /// <remarks/>
    public decimal vCOFINS {
        get {
            return this.vCOFINSField;
        }
        set {
            this.vCOFINSField = value;
            this.RaisePropertyChanged("vCOFINS");
        }
    }
    
    /// <remarks/>
    public decimal vOutro {
        get {
            return this.vOutroField;
        }
        set {
            this.vOutroField = value;
            this.RaisePropertyChanged("vOutro");
        }
    }
    
    /// <remarks/>
    public decimal vNF {
        get {
            return this.vNFField;
        }
        set {
            this.vNFField = value;
            this.RaisePropertyChanged("vNF");
        }
    }
    
    /// <remarks/>
    public decimal vTotTrib {
        get {
            return this.vTotTribField;
        }
        set {
            this.vTotTribField = value;
            this.RaisePropertyChanged("vTotTrib");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeTransp : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte modFreteField;
    
    /// <remarks/>
    public byte modFrete {
        get {
            return this.modFreteField;
        }
        set {
            this.modFreteField = value;
            this.RaisePropertyChanged("modFrete");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeCobr : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFeCobrFat fatField;
    
    private nfeProcNFeInfNFeCobrDup dupField;
    
    /// <remarks/>
    public nfeProcNFeInfNFeCobrFat fat {
        get {
            return this.fatField;
        }
        set {
            this.fatField = value;
            this.RaisePropertyChanged("fat");
        }
    }
    
    /// <remarks/>
    public nfeProcNFeInfNFeCobrDup dup {
        get {
            return this.dupField;
        }
        set {
            this.dupField = value;
            this.RaisePropertyChanged("dup");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeCobrFat : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ushort nFatField;
    
    private decimal vOrigField;
    
    private decimal vDescField;
    
    private decimal vLiqField;
    
    /// <remarks/>
    public ushort nFat {
        get {
            return this.nFatField;
        }
        set {
            this.nFatField = value;
            this.RaisePropertyChanged("nFat");
        }
    }
    
    /// <remarks/>
    public decimal vOrig {
        get {
            return this.vOrigField;
        }
        set {
            this.vOrigField = value;
            this.RaisePropertyChanged("vOrig");
        }
    }
    
    /// <remarks/>
    public decimal vDesc {
        get {
            return this.vDescField;
        }
        set {
            this.vDescField = value;
            this.RaisePropertyChanged("vDesc");
        }
    }
    
    /// <remarks/>
    public decimal vLiq {
        get {
            return this.vLiqField;
        }
        set {
            this.vLiqField = value;
            this.RaisePropertyChanged("vLiq");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeCobrDup : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte nDupField;
    
    private System.DateTime dVencField;
    
    private decimal vDupField;
    
    /// <remarks/>
    public byte nDup {
        get {
            return this.nDupField;
        }
        set {
            this.nDupField = value;
            this.RaisePropertyChanged("nDup");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dVenc {
        get {
            return this.dVencField;
        }
        set {
            this.dVencField = value;
            this.RaisePropertyChanged("dVenc");
        }
    }
    
    /// <remarks/>
    public decimal vDup {
        get {
            return this.vDupField;
        }
        set {
            this.vDupField = value;
            this.RaisePropertyChanged("vDup");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFePag : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcNFeInfNFePagDetPag detPagField;
    
    private decimal vTrocoField;
    
    /// <remarks/>
    public nfeProcNFeInfNFePagDetPag detPag {
        get {
            return this.detPagField;
        }
        set {
            this.detPagField = value;
            this.RaisePropertyChanged("detPag");
        }
    }
    
    /// <remarks/>
    public decimal vTroco {
        get {
            return this.vTrocoField;
        }
        set {
            this.vTrocoField = value;
            this.RaisePropertyChanged("vTroco");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFePagDetPag : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte tPagField;
    
    private decimal vPagField;
    
    /// <remarks/>
    public byte tPag {
        get {
            return this.tPagField;
        }
        set {
            this.tPagField = value;
            this.RaisePropertyChanged("tPag");
        }
    }
    
    /// <remarks/>
    public decimal vPag {
        get {
            return this.vPagField;
        }
        set {
            this.vPagField = value;
            this.RaisePropertyChanged("vPag");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcNFeInfNFeInfAdic : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string infCplField;
    
    /// <remarks/>
    public string infCpl {
        get {
            return this.infCplField;
        }
        set {
            this.infCplField = value;
            this.RaisePropertyChanged("infCpl");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class Signature : object, System.ComponentModel.INotifyPropertyChanged {
    
    private SignatureSignedInfo signedInfoField;
    
    private string signatureValueField;
    
    private SignatureKeyInfo keyInfoField;
    
    /// <remarks/>
    public SignatureSignedInfo SignedInfo {
        get {
            return this.signedInfoField;
        }
        set {
            this.signedInfoField = value;
            this.RaisePropertyChanged("SignedInfo");
        }
    }
    
    /// <remarks/>
    public string SignatureValue {
        get {
            return this.signatureValueField;
        }
        set {
            this.signatureValueField = value;
            this.RaisePropertyChanged("SignatureValue");
        }
    }
    
    /// <remarks/>
    public SignatureKeyInfo KeyInfo {
        get {
            return this.keyInfoField;
        }
        set {
            this.keyInfoField = value;
            this.RaisePropertyChanged("KeyInfo");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private SignatureSignedInfoCanonicalizationMethod canonicalizationMethodField;
    
    private SignatureSignedInfoSignatureMethod signatureMethodField;
    
    private SignatureSignedInfoReference referenceField;
    
    /// <remarks/>
    public SignatureSignedInfoCanonicalizationMethod CanonicalizationMethod {
        get {
            return this.canonicalizationMethodField;
        }
        set {
            this.canonicalizationMethodField = value;
            this.RaisePropertyChanged("CanonicalizationMethod");
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoSignatureMethod SignatureMethod {
        get {
            return this.signatureMethodField;
        }
        set {
            this.signatureMethodField = value;
            this.RaisePropertyChanged("SignatureMethod");
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoReference Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
            this.RaisePropertyChanged("Reference");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoCanonicalizationMethod : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
            this.RaisePropertyChanged("Algorithm");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoSignatureMethod : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
            this.RaisePropertyChanged("Algorithm");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReference : object, System.ComponentModel.INotifyPropertyChanged {
    
    private SignatureSignedInfoReferenceTransform[] transformsField;
    
    private SignatureSignedInfoReferenceDigestMethod digestMethodField;
    
    private string digestValueField;
    
    private string uRIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public SignatureSignedInfoReferenceTransform[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
            this.RaisePropertyChanged("Transforms");
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoReferenceDigestMethod DigestMethod {
        get {
            return this.digestMethodField;
        }
        set {
            this.digestMethodField = value;
            this.RaisePropertyChanged("DigestMethod");
        }
    }
    
    /// <remarks/>
    public string DigestValue {
        get {
            return this.digestValueField;
        }
        set {
            this.digestValueField = value;
            this.RaisePropertyChanged("DigestValue");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
            this.RaisePropertyChanged("URI");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReferenceTransform : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
            this.RaisePropertyChanged("Algorithm");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReferenceDigestMethod : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
            this.RaisePropertyChanged("Algorithm");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureKeyInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private SignatureKeyInfoX509Data x509DataField;
    
    /// <remarks/>
    public SignatureKeyInfoX509Data X509Data {
        get {
            return this.x509DataField;
        }
        set {
            this.x509DataField = value;
            this.RaisePropertyChanged("X509Data");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureKeyInfoX509Data : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string x509CertificateField;
    
    /// <remarks/>
    public string X509Certificate {
        get {
            return this.x509CertificateField;
        }
        set {
            this.x509CertificateField = value;
            this.RaisePropertyChanged("X509Certificate");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcProtNFe : object, System.ComponentModel.INotifyPropertyChanged {
    
    private nfeProcProtNFeInfProt infProtField;
    
    private decimal versaoField;
    
    /// <remarks/>
    public nfeProcProtNFeInfProt infProt {
        get {
            return this.infProtField;
        }
        set {
            this.infProtField = value;
            this.RaisePropertyChanged("infProt");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
            this.RaisePropertyChanged("versao");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class nfeProcProtNFeInfProt : object, System.ComponentModel.INotifyPropertyChanged {
    
    private byte tpAmbField;
    
    private string verAplicField;
    
    private string chNFeField;
    
    private System.DateTime dhRecbtoField;
    
    private ulong nProtField;
    
    private string digValField;
    
    private byte cStatField;
    
    private string xMotivoField;
    
    private string idField;
    
    /// <remarks/>
    public byte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
            this.RaisePropertyChanged("tpAmb");
        }
    }
    
    /// <remarks/>
    public string verAplic {
        get {
            return this.verAplicField;
        }
        set {
            this.verAplicField = value;
            this.RaisePropertyChanged("verAplic");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string chNFe {
        get {
            return this.chNFeField;
        }
        set {
            this.chNFeField = value;
            this.RaisePropertyChanged("chNFe");
        }
    }
    
    /// <remarks/>
    public System.DateTime dhRecbto {
        get {
            return this.dhRecbtoField;
        }
        set {
            this.dhRecbtoField = value;
            this.RaisePropertyChanged("dhRecbto");
        }
    }
    
    /// <remarks/>
    public ulong nProt {
        get {
            return this.nProtField;
        }
        set {
            this.nProtField = value;
            this.RaisePropertyChanged("nProt");
        }
    }
    
    /// <remarks/>
    public string digVal {
        get {
            return this.digValField;
        }
        set {
            this.digValField = value;
            this.RaisePropertyChanged("digVal");
        }
    }
    
    /// <remarks/>
    public byte cStat {
        get {
            return this.cStatField;
        }
        set {
            this.cStatField = value;
            this.RaisePropertyChanged("cStat");
        }
    }
    
    /// <remarks/>
    public string xMotivo {
        get {
            return this.xMotivoField;
        }
        set {
            this.xMotivoField = value;
            this.RaisePropertyChanged("xMotivo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("Id");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
