CREATE OR REPLACE VIEW PBI_VWFUNCIONARIOS AS
SELECT
    H.DTHISTSAL,
    H.IDHISTSAL,
    H.CODSINDI,
    H.CODSETOR,
    H.CODSECAO,
    H.CODDEPTO,
    H.CODAREA,
    H.CODFUNCAO,
    H.CODCARGO,
    H.MOTIVOHISTSAL,
    H.SALBASE,
    H.SALAUX1,
    H.SALAUX2,
    H.SALAUX3,
    H.DTALTERHISTSAL,
    H.DTEXCLHISTSAL,
    H.NOMEUSUINCLHISTSAL,
    H.NOMEUSUEXCLHISTSAL,
    H.DTHISTSALANT,
    H.IDHISTSALANT,
    H.CODSINDI2,
    F."CODINTFUNC",F."CODIGOUF",F."CODRACA",F."CODVINC",F."CODREGIAO",F."CODBANCO",F."CODIGOEMPRESA",F."CODAGENCIA",F."CODIGOFL",F."CODFUNC",F."CODTPADM",F."CODESTCIV",F."CODINSTR",F."CODNAC",F."CODASMED_BKP",F."CONTSINDIFUNC",F."TIPOFUNC",F."CONTACORFUNC",F."FONEFUNC",F."LOCALNASTOFUNC",F."APELIDOFUNC",F."ENDBAIRROFUNC",F."ENDCIDADEFUNC",F."NOMEFUNC",F."ENDRUAFUNC",F."ENDCOMPLFUNC",F."DIASEXPERFUNC",F."DTADMFUNC",F."DTNASCTOFUNC",F."DTTRANSFFUNC",F."SOCIOSINDIFUNC",F."SITUACAOFUNC",F."RECEBEADTFUNC",F."INCINSSFUNC",F."INCIRFFUNC",F."INCFGTSFUNC",F."CESTABASICAFUNC",F."VALEREFEICFUNC",F."SEXOFUNC",F."JORNADAFUNC",F."ENDNRFUNC",F."DTAPOSENTFUNC",F."ENDCEPFUNC",F."ENDPTREFERFUNC",F."EMITEXTRFUNC",F."TIPOSANGUEFUNC",F."EMAILFUNC",F."IMPRCARTPTOFUNC",F."BATEPTOELETRFUNC",F."LIVRODEPTOFUNC",F."ESCALAREVEZFUNC",F."TEMFREQUENFUNC",F."CHAPAFUNC",F."SENHACARTAOFUNC",F."NOMECOMPLETOFUNC",F."CODIGOUFNASCTO",F."DATAAVISOPREVIOFUNC",F."TEMCOMPLEMFUNC",F."TIPOAVISOFUNC",F."CODINTANTERIOR",F."TIPOCONTA",F."DIASPRORROGACAOFUNC",F."FONE2FUNC",F."CODMOTAPOSENT",F."CODGARSAL",F."USUARIOALTER",F."CODHORA_BKP",F."CODESCALA_BKP",F."CODINTCUR",F."COD_REGIME",F."CODTIPOCONTRATO",F."DATATERMINOCONTRATO",F."CODVINCULO",F."CODREGIMEPREV",F."CASAPROPRIA",F."ADQUIRIDOFGTS",F."CODCATEGORIA",F."CODLOGRADOURO",F."CATEGORIACOOPERADO",F."CODMUNIC",F."CODMUNICNASCTO",F."CODDETALHENAC",
    U.DESCFUNCAOCOMPLETA,
    U.TPSALFUNCAO,
    U.HRSEMFUNCAO,
    U.HRSEMAUX1FUNCAO,
    U.HRSEMAUX2FUNCAO,
    U.HRSEMAUX3FUNCAO,
    U.TPSALAUX1FUNCAO,
    U.TPSALAUX2FUNCAO,
    U.TPSALAUX3FUNCAO,
    U.DESCFUNCAO,
    UF.DESCRICAOUF,
    BC.NOMEBANCO,
    NC.DESCNAC,
    GI.DESCINSTR,
    EC.DESCESTCIV,
    SI.DESCSINDI,
    AR.DESCAREA,
    DE.DESCDEPTO,
    SE.DESCSETOR,
    SC.DESCSECAO,
    TA.DESCTPADM,
    H.SALAUX4,
    H.SALAUX5,
    H.SALAUX6,
    U.HRSEMAUX4FUNCAO,
    U.HRSEMAUX5FUNCAO,
    U.HRSEMAUX6FUNCAO,
    U.TPSALAUX4FUNCAO,
    U.TPSALAUX5FUNCAO,
    U.TPSALAUX6FUNCAO,
    SUBSTR(FUNC_TRAZSITUACAOFUNC(F.CODINTFUNC, C.COMPETENCIA, 'F','',F.DTADMFUNC,F.SITUACAOFUNC,F.DTTRANSFFUNC),1,1) SITUACAONACOMPET,
    C.COMPETENCIA
  FROM
    FLP_HISTORICOSALARIAL H,
    FLP_FUNCIONARIOS F ,
    FLP_FUNCAO U,
    FLP_AREA AR,
    FLP_DEPTO DE,
    FLP_SETOR SE,
    FLP_SECAO SC,
    FLP_SINDICATOS SI,
    FLP_NACIONALIDADES NC,
    BCOBANCO BC,
    BGM_CADUF UF,
    FLP_INSTRUCAO GI,
    FLP_ESTADOCIVIL EC,
    FLP_TIPOADMISSAO TA,
    CTR_FILIAL FL,
    VW_COMPETENCIATERMINAL C
  WHERE
    (F.CODINTFUNC    = H.CODINTFUNC) AND
    (U.CODFUNCAO     = H.CODFUNCAO)  AND
    (SI.CODSINDI     = H.CODSINDI)   AND
    (AR.CODAREA      = H.CODAREA)    AND
    (DE.CODDEPTO     = H.CODDEPTO)   AND
    (SE.CODSETOR     = H.CODSETOR)   AND
    (SC.CODSECAO     = H.CODSECAO)   AND
    (UF.CODIGOUF(+)  = F.CODIGOUF)   AND
    (BC.CODBANCO(+)  = F.CODBANCO)   AND
    (NC.CODNAC(+)    = F.CODNAC)     AND
    (GI.CODINSTR(+)  = F.CODINSTR)   AND
    (EC.CODESTCIV(+) = F.CODESTCIV)  AND
    (TA.CODTPADM(+)  = F.CODTPADM)   AND
    (H.STATUSHISTSAL = 'N') AND
    (H.DTHISTSAL     = (SELECT
                          MAX(FLP_HISTORICOSALARIAL.DTHISTSAL)
                        FROM
                          FLP_HISTORICOSALARIAL
                        WHERE
                          (FLP_HISTORICOSALARIAL.DTHISTSAL <= C.COMPETENCIA) AND
                          (FLP_HISTORICOSALARIAL.STATUSHISTSAL  = 'N') AND
                          (FLP_HISTORICOSALARIAL.CODINTFUNC = F.CODINTFUNC))) AND
    (FL.CODIGOFL = F.CODIGOFL) AND
    (FL.CODIGOEMPRESA = F.CODIGOEMPRESA)

