create or replace view pbi_arr_receita_media as
Select Empresa,
       Empfil,
       Last_Day(Data) Data,
       Sum(Vlr_Faturamento) Vlr_Faturamento,
       Sum(Passageiros) Passageiros,
       Sum(Qtdsab) Qtdsab,
       Sum(Qtddom) Qtddom,
       Sum(Qtddu) Qtddu,
       Sum(Fatsabado) Fatsabado,
       Sum(Fatdomingo) Fatdomingo,
       Sum(Fatdu) Fatdu,
       Decode(Sum(QtdSab), 0, 0, Round(Sum(FatSabado) / Sum(QtdSAB),2))  Mediafatsabado,
       Decode(Sum(QtdDOM), 0, 0, Round(Sum(FatDomingo) / Sum(QtdDOM),2)) MediaFatDomingo,
       Decode(Sum(QtdDu), 0, 0, Round(Sum(FatDU) / Sum(QtdDu),2)) MediaFatDU,

       Decode(Sum(QtdSab), 0, 0, Round(Sum(PassSabado) / Sum(QtdSAB),2))  MediaPasssabado,
       Decode(Sum(QtdDOM), 0, 0, Round(Sum(PassDomingo) / Sum(QtdDOM),2)) MediaPAssDomingo,
       Decode(Sum(QtdDu), 0, 0,Round(Sum(PassDU) / Sum(QtdDu),2)) MediaPassDU,

       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassDU) / Sum(QtdDu))/ To_char(Sysdate,'mm'),2), 0)) MediaPassDUAnoAtual,
       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassDU) / Sum(QtdDu))/12,2), 0)) MediaPassDUAnoAnterior,
       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassDU) / Sum(QtdDu))/12,2), 0)) MediaPassDUAno2Anterior,

       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassSabado) / Sum(QtdSAB))/ To_char(Sysdate,'mm'),2), 0)) MediaPassSabAnoAtual,
       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassSabado) / Sum(QtdSAB))/12,2), 0)) MediaPassSabAnoAnterior,
       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassSabado) / Sum(QtdSAB))/12,2), 0)) MediaPassSabAno2Anterior,

       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassDomingo) / Sum(QtdDOM))/ To_char(Sysdate,'mm'),2), 0)) MediaPassDomAnoAtual,
       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassDomingo) / Sum(QtdDOM))/12,2), 0)) MediaPassDomAnoAnterior,
       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassDomingo) / Sum(QtdDOM))/12,2), 0)) MediaPassDomAno2Anterior

  From ((Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Eovgdutra) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Eovglavras) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Abc) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Rapido) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Cisne) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Aruja) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Campibus) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Ribe) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Vugdutra) Union All
        (Select Empresa,
                Empfil,
                Data,
                Vlr_Faturamento,
                Passageiros,
                Mediapassageiros,
                Mediafaturamento,
                Qtdsab,
                Fatsabado,
                Passsabado,
                Qtddom,
                Fatdomingo,
                Passdomingo,
                Qtddu,
                Fatdu,
                Passdu
           From Pbi_Arr_Receita_Vugbebedouro))
 Group By Empresa, Empfil, Last_Day(Data)

