CREATE OR REPLACE VIEW VW_NIFF_PROXIMO_EXAME AS
SELECT A.CODINTFUNC, A.DATAFICHAMED, MAX(TRUNC(TO_DATE(A.DTPROXEXAMEDIGIT,'DD-MON-YY'))) PROXIMO

         FROM GLOBUS.SRH_FICHAMEDICA_EXAMES A,
             (
              SELECT X.CODINTFUNC,MAX(X.DATAFICHAMED) DATAFICHAMED
              FROM GLOBUS.SRH_FICHAMEDICA X
                   WHERE X.TIPOCONSULTA IN (2,4,7)
              GROUP BY X.CODINTFUNC
              ) B

              WHERE A.DATAFICHAMED = B.DATAFICHAMED

                AND A.CODINTFUNC = B.CODINTFUNC

         GROUP BY A.CODINTFUNC, A.DATAFICHAMED

