CREATE OR REPLACE VIEW VW_NIFF_MAN_COMSUMOOLEO AS
SELECT V.CODIGOEMPRESA,
       V.CODIGOFL,
       R.DATARQ,
       V.CODGRPREV,
       O.NUMEROOS,
       R.CODINTOS,
       V.PREFIXOVEIC,
       V.CODIGOVEIC,
       R.NUMERORQ,
       M.CODIGOINTERNOMATERIAL,
       I.QTDEITREQ

FROM GLOBUS.EST_REQUISICAO R,
     GLOBUS.FRT_CADVEICULOS V,
     GLOBUS.EST_ITENSREQUISICAO I,
     GLOBUS.EST_CADMATERIAL M,
     GLOBUS.MAN_OS O

     WHERE R.CODIGOVEIC = V.CODIGOVEIC
       AND R.NUMERORQ = I.NUMERORQ
       AND I.CODIGOMATINT = M.CODIGOMATINT

       AND O.CODIGOEMPRESA = R.CODIGOEMPRESA
       AND O.CODIGOEMPRESA = V.CODIGOEMPRESA
       AND R.CODIGOEMPRESA = V.CODIGOEMPRESA

       AND O.CODIGOFL = R.CODIGOFL
       AND O.CODIGOFL = V.CODIGOFL
       AND R.CODIGOFL = V.CODIGOFL

       AND R.CODINTOS = O.CODINTOS

       AND V.CONDICAOVEIC = 'A'
       AND M.CODIGOGRD = 0530
       AND NOT V.CODIGOTPVEIC IN (71,74)
       AND NOT V.CODIGOTPFROTA IN (10,52)
       AND V.APRESENTARELATORIOVEIC = 'S'

 ORDER BY V.CODIGOEMPRESA,
          V.CODIGOFL,
          M.CODIGOINTERNOMATERIAL,
          R.DATARQ,
          V.PREFIXOVEIC,
          V.CODIGOVEIC

