-- Man - Retrabalho sql BSP
SELECT PREVENTIVA.EMPRESA, PREVENTIVA.PREFIXOVEIC, to_char(PREVENTIVA.DT_PREV) DT_PREV, CORRETIVA.OS_COR, CORRETIVA.DT_COR

FROM

(SELECT M.CODIGOEMPRESA, M.CODIGOFL, M.CODIGOVEIC, M.Numeroos OS_COR, M.DATAABERTURAOS DT_COR
 FROM   MAN_OS M
 WHERE  M.CODIGOEMPRESA = 2 AND M.CODIGOFL = 1 AND
        M.TIPOOS = 'C')CORRETIVA,

(SELECT PREVENTIVA.EMPRESA, PREVENTIVA.CODIGOVEIC, PREVENTIVA.PREFIXOVEIC, PREVENTIVA.DATA_OS DT_PREV

FROM
((SELECT /*+ RULE */ 
  '002/001 ABC TRANSPORTES' EMPRESA,
  'REVISAO PESADA' TITULO,
  OS.CODIGOVEIC,
  PREFIXOVEIC, 
  OS.DATA DATA_OS
FROM 
  ( 
   SELECT 
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 2 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 2 
     GROUP BY
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (42)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 2 AND C.CODIGOFL = 1    AND
    D.CODIGOPLANREV IN (42)                   AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 2 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
  (OS.KMEXCESSO > -30000 and OS.KMEXCESSO < 0)
GROUP by   PREFIXOVEIC,   OS.CODIGOVEIC, OS.DATA
)) PREVENTIVA) PREVENTIVA

WHERE CORRETIVA.CODIGOVEIC = PREVENTIVA.CODIGOVEIC
AND   CORRETIVA.DT_COR > PREVENTIVA.DT_PREV 