Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'GARANTIA ¿ EXECU«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'MANDATO DE CITA«√O E PENHORA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'APELA«√O E CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'AGRAVO DE INSTRUMENTO E CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSOS E CUSTOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'DEP”SITO GARANTIA A EXECU«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'DARF','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS CONTADOR','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO ADESIVO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'PENS„O MENSAL','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'CUSTOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'OUTROS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS ADVOCATÕCIOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'INSS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS DE SUCUMB NCIA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'GPS (Guia PrevidÍncia Social)','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS PERICIAIS PRÈVIOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'IMPOSTO DE RENDA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'PAGAMENTO DA EXECU«√O (30% + 6 PARCELAS)','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO ORDIN¡RIO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS PERICIAIS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'AGRAVO DE INSTRUMENTO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO EXTRAORDIN¡RIO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS ASSISTENTE T…CNICO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS CONTADOR PRÈVIOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'OUTROS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'PENS√O VITALÕCIA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'PAGAMENTO DA EXECU«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'CARTA PRECAT”RIA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'HONOR¡RIOS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO DE REVISTA E CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'GARANTIA DA EXECU«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'CUMPRIMENTO DE LIMINAR - DESPESAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'ACORDO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'REEMBOLSO DE DESPESAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO ESPECIAL E CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'PAGAMENTO ¿ EXECU«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'APELA«√O','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO DE REVISTA','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'VERBAS RESCISÛRIAS - CONSIGNA«√O EM PAGAMENTO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO ORDIN¡RIO E CUSTAS','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'GUIA DE OFICIAL DE JUSTI«A','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO INOMINADO','S');
Insert into Niff_Jur_Tipo ( idtipo, descricao, ativo )  Values ( SQ_NIFF_JurIdTipo.NextVal, 'RECURSO ESPECIAL','S');