insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(1,'1.1',1,3,'Direção Perigosa','Motorista efetuar curvas perigosas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(10,'1.10',1,3,'Direção Perigosa','Motorista trafegar com morosidade');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(11,'1.11',1,3,'Direção Perigosa','Motorista trafegar em alta velocidade');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(12,'1.12',1,3,'Direção Perigosa','Colisão entre veículos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(13,'1.13',1,3,'Direção Perigosa','Atropelamento');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(2,'1.2',1,3,'Direção Perigosa','Motorista efetuar manobras perigosas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(3,'1.3',1,3,'Direção Perigosa','Motorista efetuar ultrapassagens perigosas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(4,'1.4',1,3,'Direção Perigosa','Motorista frear bruscamente');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(5,'1.5',1,3,'Direção Perigosa','Motorista não aguardar total desembarque do usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(6,'1.6',1,3,'Direção Perigosa','Motorista não aguardar total embarque do usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(7,'1.7',1,3,'Direção Perigosa','Motorista não respeitar sinalização semafórica');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(8,'1.8',1,3,'Direção Perigosa','Motorista passar bruscamente por lombadas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(9,'1.9',1,3,'Direção Perigosa','Motorista prender usuário na porta do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(49,'10.1',1,3,'Terminal','Ausência do fiscal no Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(50,'10.2',1,3,'Terminal','Ausência do ponto de parada no Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(51,'10.3',1,3,'Terminal','Falta de comunicação visual no Terminal para identificação das linhas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(52,'10.4',1,3,'Terminal','Falta de organização das filas de embarque');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(53,'10.5',1,3,'Terminal','Mudança de Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(54,'10.6',1,3,'Terminal','Manutenção de equipamentos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(162,'100.0',4,1,'INFORMAÇÃO','GENÉRICA');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(55,'11.1',3,3,'Tripulação/Funcionário','Bilheteira recusar vender bilhete eletrônico');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(64,'11.10',1,3,'Tripulação/Funcionário','Motorista fumar no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(65,'11.11',1,3,'Tripulação/Funcionário','Motorista namorar no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(66,'11.12',1,3,'Tripulação/Funcionário','Motorista não permitir embarque de bagagem de usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(67,'11.13',1,3,'Tripulação/Funcionário','Motorista receber o valor da passagem e não girar a catraca');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(68,'11.14',1,3,'Tripulação/Funcionário','Rádio com volume e alto no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(69,'11.15',1,3,'Tripulação/Funcionário','Usuário fumar no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(70,'11.16',1,3,'Tripulação/Funcionário','Motorista permitir o uso indevido de assento reservado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(71,'11.17',1,3,'Tripulação/Funcionário','Motorista interromper a viagem');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(72,'11.18',1,3,'Tripulação/Funcionário','Motorista não permitir desembarque gratuito de integrante das Forças Armadas uniformizado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(73,'11.19',1,3,'Tripulação/Funcionário','Motorista não permitir embarque de usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(56,'11.2',1,3,'Tripulação/Funcionário','Cobrador agredir fisicamente o usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(74,'11.20',1,3,'Tripulação/Funcionário','Motorista não permitir desembarque de usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(75,'11.21',1,3,'Tripulação/Funcionário','Motorista agredir usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(76,'11.22',1,3,'Tripulação/Funcionário','Comportamento inadequado de funcionários');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(77,'11.23',1,3,'Tripulação/Funcionário','Comportamento inadequado de motorista');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(78,'11.24',1,3,'Tripulação/Funcionário','Motorista estacionar veículo em local inadequado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(79,'11.25',1,3,'Tripulação/Funcionário','Comportamento inadequado de cobrador');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(80,'11.26',1,3,'Tripulação/Funcionário','Motorista não efetuar parada ao lado da cobertura');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(81,'11.27',1,3,'Tripulação/Funcionário','Motorista permitir excesso de bagagem no interior do veículo (produto inflamável)');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(82,'11.28',1,3,'Tripulação/Funcionário','Motorista não permitir desembarque de passageiro credenciado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(83,'11.29',1,3,'Tripulação/Funcionário','Colaborador não saber manusear o elevador do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(57,'11.3',1,3,'Tripulação/Funcionário','Cobrador com sintomas de embriaguez');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(58,'11.4',1,3,'Tripulação/Funcionário','Cobrador fumar no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(59,'11.5',1,3,'Tripulação/Funcionário','Cobrador namorar no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(60,'11.6',1,3,'Tripulação/Funcionário','Cobrador receber o valor da passagem e não girar a catraca');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(61,'11.7',1,3,'Tripulação/Funcionário','Motorista com sintomas de embriaguez');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(62,'11.8',1,3,'Tripulação/Funcionário','Motorista conversar com usuário atrasando a viagem');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(63,'11.9',1,3,'Tripulação/Funcionário','Motorista fazer necessidades fisiológicas nos muros do Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(84,'12.1',5,3,'Veículo','Falta de comunicação visual no veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(93,'12.10',5,3,'Veículo','Veículo com piso molhado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(94,'12.11',5,3,'Veículo','Veículo com piso solto');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(95,'12.12',5,3,'Veículo','Veículo com problemas de freio');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(96,'12.13',5,3,'Veículo','Veículo em condições insatisfatórias de conservação');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(97,'12.14',5,3,'Veículo','Veículo em condições insatisfatórias de higiene');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(98,'12.15',5,3,'Veículo','Veículo em condições insatisfatórias de manutenção');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(99,'12.16',5,3,'Veículo','Reclamação sobre os letreiros e placas incorretas/ausentes ');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(100,'12.17',5,3,'Veículo','Substituição de veículo de microônibus para ônibus convencional');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(101,'12.18',5,3,'Veículo','Manutenção');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(102,'12.19',5,3,'Veículo','Reclamação sobre ar-condicionado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(85,'12.2',5,3,'Veículo','Falta de adesivo de tarifa no interior do veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(103,'12.20',5,3,'Veículo','Veículo com problemas no elevador');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(104,'12.21',5,3,'Veículo','OUTRAS');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(86,'12.3',5,3,'Veículo','Veículo com ausência de vidro');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(87,'12.4',5,3,'Veículo','Veículo com balaustre solto');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(88,'12.5',5,3,'Veículo','Veículo com banco rasgado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(89,'12.6',5,3,'Veículo','Veículo com banco sujo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(90,'12.7',5,3,'Veículo','Veículo com banco úmido');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(91,'12.8',5,3,'Veículo','Veículo com parabrisa trincado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(92,'12.9',5,3,'Veículo','Veículo com piso danificado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(105,'13.1',3,3,'Passe Escolar','Empresa recusar-se vender passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(106,'13.2',3,3,'Passe Escolar','Empresa recusar-se a trocar passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(107,'14.1',1,3,'Fiscalização','Solicitação de fiscalização');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(108,'15.1',4,3,'Resposta de Reclamação','Resposta de reclamação insatisfatória');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(109,'15.2',4,3,'Resposta de Reclamação','Solicitação de resposta ');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(110,'16.1',4,3,'Acesso ao SAC','Impossibilidade de contato com a SAC');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(111,'17.1',1,3,'Pontos de Parada','Implantação de ponto de parada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(112,'17.2',1,3,'Pontos de Parada','Mudança de ponto de parada de ônibus ou táxi');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(113,'17.3',1,3,'Pontos de Parada','Instalação de abrigo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(114,'17.4',1,3,'Pontos de Parada','Manutenção de ponto de parada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(115,'17.5',1,3,'Pontos de Parada','Remoção de abrigo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(116,'18.1',1,3,'Carona','Reclamação de carona');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(117,'19.1',4,3,'Outras','Reclamações outras');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(118,'19.2',1,3,'Outras','Tarifa');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(14,'2.1',1,3,'Horário Irregular/Atraso','Intervalo entre partidas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(15,'2.2',1,3,'Horário Irregular/Atraso','Partida antecipada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(16,'2.3',1,3,'Horário Irregular/Atraso','Partida com atraso');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(17,'2.4',1,3,'Horário Irregular/Atraso','Partida não realizada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(119,'20.1',1,4,'Elogio','Horário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(128,'20.10',3,4,'Elogio','Acesso ao SAC');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(129,'20.11',1,4,'Elogio','Pontos de parada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(130,'20.12',1,4,'Elogio','Outros');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(120,'20.2',1,4,'Elogio','Itinerário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(121,'20.3',1,4,'Elogio','Passageiro especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(122,'20.4',1,4,'Elogio','Tarifa');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(123,'20.5',1,4,'Elogio','Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(124,'20.6',5,4,'Elogio','Veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(125,'20.7',1,4,'Elogio','Tripulação/funcionário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(126,'20.8',3,4,'Elogio','Passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(127,'20.9',3,4,'Elogio','Vale-Transporte');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(163,'200.0',4,2,'SUGESTÃO','GENÉRICA');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(131,'21.1',1,2,'Sugestão','Horário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(140,'21.10',4,2,'Sugestão','Acesso ao SAC');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(141,'21.11',1,2,'Sugestão','Pontos de parada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(142,'21.12',1,2,'Sugestão','Ampliação de oferta na linha');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(143,'21.13',1,2,'Sugestão','Criação de linhas');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(144,'21.14',1,2,'Sugestão','Ampliação da extensão da linha');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(145,'21.15',1,2,'Sugestão','Outras');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(132,'21.2',1,2,'Sugestão','Itinerário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(133,'21.3',1,2,'Sugestão','Passageiro especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(134,'21.4',1,2,'Sugestão','Tarifa');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(135,'21.5',1,2,'Sugestão','Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(136,'21.6',5,2,'Sugestão','Veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(137,'21.7',2,2,'Sugestão','Tripulação/funcionário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(138,'21.8',3,2,'Sugestão','Passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(139,'21.9',3,2,'Sugestão','Vale-transporte');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(146,'22.1',4,1,'Informação','Horário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(155,'22.10',4,1,'Informação','Pontos de parada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(156,'22.11',4,1,'Informação','Outras');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(157,'22.12',4,1,'Informação','Achados e perdidos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(158,'22.13',4,1,'Informação','Tempo de percurso');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(159,'22.14',4,1,'Informação','Colisão');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(147,'22.2',4,1,'Informação','Itinerário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(148,'22.3',4,1,'Informação','Passageiro especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(149,'22.4',4,1,'Informação','Tarifa');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(150,'22.5',4,1,'Informação','Terminal');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(151,'22.6',4,1,'Informação','Veículo');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(152,'22.7',4,1,'Informação','Passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(153,'22.8',4,1,'Informação','Vale-transporte');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(154,'22.9',4,1,'Informação','Acesso ao SAC');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(160,'23.1',4,1,'Chamada Perdida','Chamada perdida');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(18,'3.1',1,3,'Inobservância de Ponto','Motorista não atender sinal de parada para desembarque');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(19,'3.2',1,3,'Inobservância de Ponto','Motorista não atender sinal de parada para embarque');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(20,'3.3',1,3,'Inobservância de Ponto','Motorista parar fora do ponto solicitado');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(21,'3.4',1,3,'Inobservância de Ponto','Motorista trafegar pela faixa da esquerda');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(22,'3.5',1,3,'Inobservância de Ponto','Motorista ultrapassar veículo parado no ponto');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(164,'300.0',4,3,'RECLAMAÇÃO','GENÉRICA');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(23,'4.1',1,3,'Itinerário','Desvio de itinerário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(165,'400.0',4,4,'ELOGIO','GENÉRICA');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(24,'5.1',1,3,'Mau Atendimento ao Idoso','Cobrador destratar usuário idoso');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(25,'5.2',1,3,'Mau Atendimento ao Idoso','Cobrador não permitir desembarque de usuário maior de 65 anos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(26,'5.3',1,3,'Mau Atendimento ao Idoso','Cobrador não permitir o embarque de usuário maior de 65 anos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(27,'5.4',1,3,'Mau Atendimento ao Idoso','Motorista maltratar usuário idoso');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(28,'5.5',1,3,'Mau Atendimento ao Idoso','Motorista não permitir embarque de usuário maior de 65 anos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(29,'5.6',1,3,'Mau Atendimento ao Idoso','Motorista não permitir o desembarque de usuário maior de 65 anos');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(30,'6.1',1,3,'Ofensa ao Usuário','Cobrador destratar usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(31,'6.2',1,3,'Ofensa ao Usuário','Motorista destratar usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(32,'6.3',1,3,'Ofensa ao Usuário','Fiscal destratar usuário');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(33,'7.1',1,3,'Passageiro Especial','Cobrador destratar usuário portador de Carteira de Passageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(34,'7.2',1,3,'Passageiro Especial','Cobrador não permitir embarque de acompanhante do portador de Carteira de Passageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(35,'7.3',1,3,'Passageiro Especial','Cobrador não permitir embarque de usuário portador de Carteira de Passageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(36,'7.4',1,3,'Passageiro Especial','Motorista destratar usuário portador de Carteira de Passageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(37,'7.5',1,3,'Passageiro Especial','Motorista não permitir embarque de acompanhante do portador de Carteira de Pasageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(38,'7.6',1,3,'Passageiro Especial','Motorista não permitir embarque de usuário portador de Carteira de Passageiro Especial');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(39,'8.1',1,3,'Superlotação','Superlotação');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(40,'9.1',1,3,'Tarifa','Cobrador devolver troco em vale transporte');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(41,'9.2',1,3,'Tarifa','Cobrador não aceitar passe escolar');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(42,'9.3',1,3,'Tarifa','Cobrador não aceitar vale transporte como complemento de passagem');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(43,'9.4',1,3,'Tarifa','Cobrança de tarifa superior à autorizada');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(44,'9.5',1,3,'Tarifa','Motorista desembarcar usuário por falta de troco');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(45,'9.6',1,3,'Tarifa','Cobrador não devolver troco');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(46,'9.7',3,3,'Tarifa','Reclamação sobre problemas com o cartão');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(47,'9.8',3,3,'Tarifa','Reclamação sobre problemas com o cartão estudante');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(48,'9.9',1,3,'Tarifa','Cobrador não ter troco');
insert into NIFF_CHM_EMTUAtendimento (IdEmtu, Codigo, IdDepartamento, IdTpAtendimento, Titulo, descricao)  values(166,'999.0',1,5,'Outros','Atendimentos Exógenos');