CREATE OR REPLACE VIEW PBI_ARR_RECEITA_Media AS
Select Empresa, EmpFil, Last_day(Data) Data,
       Sum(VLR_FATURAMENTO) VLR_FATURAMENTO,
       Sum(PASSAGEIROS) PASSAGEIROS,
       Sum(QtdSAB) QtdSAB,
       Sum(QtdDOM) QtdDOM,
       Sum(QtdDu) QtdDu,
       Sum(FatSabado) FatSabado,
       Sum(FatDomingo) FatDomingo,
       Sum(FatDU) FatDU,
       Decode(Sum(QtdSab), 0, 0, Round(Sum(FatSabado) / Sum(QtdSAB),2))  Mediafatsabado,
       Decode(Sum(QtdDOM), 0, 0, Round(Sum(FatDomingo) / Sum(QtdDOM),2)) MediaFatDomingo,
       Decode(Sum(QtdDu), 0, 0, Round(Sum(FatDU) / Sum(QtdDu),2)) MediaFatDU, 
       
       Decode(Sum(QtdSab), 0, 0, Round(Sum(PassSabado) / Sum(QtdSAB),2))  MediaPasssabado,
       Decode(Sum(QtdDOM), 0, 0, Round(Sum(PassDomingo) / Sum(QtdDOM),2)) MediaPAssDomingo,
       Decode(Sum(QtdDu), 0, 0,Round(Sum(PassDU) / Sum(QtdDu),2)) MediaPassDU,
       
       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassDU) / Sum(QtdDu))/ To_char(Sysdate,'mm'),2), 0)) MediaPassDUAnoAtual,
       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassDU) / Sum(QtdDu))/12,2), 0)) MediaPassDUAnoAnterior,
       Decode(Sum(QtdDu), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassDU) / Sum(QtdDu))/12,2), 0)) MediaPassDUAno2Anterior,

       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassSabado) / Sum(QtdSAB))/ To_char(Sysdate,'mm'),2), 0)) MediaPassSabAnoAtual,
       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassSabado) / Sum(QtdSAB))/12,2), 0)) MediaPassSabAnoAnterior,
       Decode(Sum(QtdSAB), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassSabado) / Sum(QtdSAB))/12,2), 0)) MediaPassSabAno2Anterior,

       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy'), Round((Sum(PassDomingo) / Sum(QtdDOM))/ To_char(Sysdate,'mm'),2), 0)) MediaPassDomAnoAtual,
       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-1, Round((Sum(PassDomingo) / Sum(QtdDOM))/12,2), 0)) MediaPassDomAnoAnterior,
       Decode(Sum(QtdDOM), 0, 0, Decode(To_Char(Last_day(Data),'yyyy'), To_Char(Last_day(Sysdate),'yyyy')-2, Round((Sum(PassDomingo) / Sum(QtdDOM))/12,2), 0)) MediaPassDomAno2Anterior

From (
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_EOVGDutra )
Union all
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_EOVGLavras )
union all
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_ABC )
union All
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_Rapido )
union all
 (Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_Cisne )
union all
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_Aruja )
union All
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_Campibus)
union all
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_Ribe)
union all
(Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_VugDutra)
union all
 (Select empresa,
        EmpFil, 
        Data,
        VLR_FATURAMENTO,
        PASSAGEIROS,
        MediaPassageiros,
        MediaFaturamento,
        QtdSAB,
        FatSabado,
        PassSabado,
        QtdDOM, 
        FatDomingo, 
        PassDomingo, 
        QtdDu, 
        FatDU,
        PassDU
   From pbi_arr_receita_VugBebedouro)
)
Group By Empresa, EmpFil, Last_day(Data)

