Select q.Qtde - b.Qtde dif, q.Qtde Qtde, b.Qtde QtdeBilhetes, q.COD_SEQ_AGENCIA, q.CODPASSE, q.CODSERIE
  From (SELECT SUM(Q.QUANTIDADE) Qtde, COD_SEQ_AGENCIA, CODPASSE, CODSERIE
          FROM VBE_QUANTIDADE Q WHERE Q.COD_SEQ_AGENCIA = 9 AND Q.CODPASSE = 1000 AND Q.CODSERIE = 'A1'
         Group By COD_SEQ_AGENCIA, CODPASSE, CODSERIE) q
     , (SELECT COUNT(B.ID_VBE_BILHETES) Qtde, COD_SEQ_AGENCIA, CODPASSE, CODSERIE
          FROM VBE_BILHETES B WHERE B.COD_SEQ_AGENCIA = 9 AND B.CODPASSE = 1000 AND B.CODSERIE = 'A1' AND B.DATASAIDA IS Null
         Group By COD_SEQ_AGENCIA, CODPASSE, CODSERIE) b
 Where q.COD_SEQ_AGENCIA = b.COD_SEQ_AGENCIA
   And q.CODPASSE = b.codpasse
   And q.CODSERIE = b.codserie;
   
  /* Select q.Qtde Qtde, b.Qtde QtdeBilhetes, q.COD_SEQ_AGENCIA, q.CODPASSE, q.CODSERIE
  From (SELECT SUM(Q.QUANTIDADE) Qtde, COD_SEQ_AGENCIA, CODPASSE, CODSERIE
          FROM VBE_QUANTIDADE Q 
          
         Group By COD_SEQ_AGENCIA, CODPASSE, CODSERIE) q
     , (SELECT COUNT(B.ID_VBE_BILHETES) Qtde, COD_SEQ_AGENCIA, CODPASSE, CODSERIE
          FROM VBE_BILHETES B WHERE B.DATASAIDA IS Null
         Group By COD_SEQ_AGENCIA, CODPASSE, CODSERIE) b
 Where q.COD_SEQ_AGENCIA = b.COD_SEQ_AGENCIA
   And q.CODPASSE = b.codpasse
   And q.CODSERIE = b.codserie;*/