SELECT * FROM CPR_ENDERECOITEMCOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_MARCAITEMCOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_ITEMCOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_UFGRPCOMPRACOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_FORNGRPCOMPRACOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_GRPCOMPRACOTACAOGLB7 A WHERE A.NRCOTA = 102099;
SELECT * FROM CPR_COTACAO_GLB7 A WHERE A.NRCOTA = 102099;
Select * From cpr_serv_g4_g7 a Where a.nrcota = 102099;
Select * From cpr_serv_g4_g7_LOG a Where a.nrcota = 102099;
SELECT  A.*, A.ROWID FROM CPR_G7_ASSOC_GPR_COMPRAS A

SELECT A.*, A.ROWID FROM CPR_PARAMINTEGRACAOGL4GL7 A

