Select (Sum(Receita) + Sum(Vlr_Txemb) + Sum(Vlr_Pedagio)) - Sum(Vlr_Outros) As Vlr_Total,
       Sum(Receita) As Receita,
       Sum(Vlr_Txemb) Vlr_Txemb,
       Sum(Vlr_Pedagio) Vlr_Pedagio,
       Sum(Vlr_Outros) Vlr_Outros,
       Sum(Vlr_Seguroi) Vlr_Seguroi,
       Sum(Vlr_Seguroni) Vlr_Seguroni,
       Cod_Agencia,
       Nom_Agencia,
       Fechasemreceitaguia,
       Flg_Recguiaagencia,
       Cod_Seq_Agencia,
       Cod_Local_Arr,
       Tpguia,
       Cod_Empresa,
       Codigofl,
       Tipolinha,
       Data,
       Classlinha,
       Tppagto_Alp,
       Tplinha,
       Classificacao,
       Filint,
       (Sum(Receita_Alp) + Sum(Vlr_Txemb_Alp) + Sum(Vlr_Pedagio_Alp)) -
       Sum(Vlr_Outros_Alp) As Vlr_Total_Alp,
       Sum(Receita_Alp) - Sum(Vlr_Seguroi_Alp) - Sum(Vlr_Seguroni_Alp) As Receita_Alp,
       Sum(Vlr_Txemb_Alp) Vlr_Txemb_Alp,
       Sum(Vlr_Pedagio_Alp) Vlr_Pedagio_Alp,
       Sum(Vlr_Outros_Alp) Vlr_Outros_Alp,
       Sum(Vlr_Seguroi_Alp) Vlr_Seguroi_Alp,
       Sum(Vlr_Seguroni_Alp) Vlr_Seguroni_Alp,
       Sum(Vlr_Tmr) Vlr_Tmr,
       Sum(Vlr_Tmr_Alp) Vlr_Tmr_Alp,
       Cod_Tipopagtarifa
  From ( /* ALP */
         Select c.Cod_Agencia,
                 c.Nom_Agencia,
                 a.Fechasemreceitaguia,
                 a.Flg_Recguiaagencia,
                 c.Cod_Seq_Agencia,
                 r.Cod_Local_Arr,
                 Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V') Tpguia,
                 g.Cod_Empresa,
                 g.Codigofl,
                 c.Codigofl_Intctb Filint,
                 Nvl(l.Codigotplinha, 9) Tipolinha,
                 Cod_Tipopagtarifa,
                 Trunc(g.Dat_Prest_Contas) Data,
                 Nvl(l.Flg_Munic_Interest, 'Z') Classlinha,
                 Pp.Codtppagto Tppagto_Alp,
                 Decode(Nvl(l.Codigotplinha, 9),
                         0,
                         'Rodoviaria',
                         1,
                         'Urbana',
                         2,
                         'Fretamento',
                         3,
                         'Suburbana',
                         'Nao cadastrado') Tplinha,
                 Decode(Nvl(l.Flg_Munic_Interest, 'Z'),
                         'M',
                         'Municipal',
                         'U',
                         'Intermunicipal'                        
                        ,
                         'I',
                         'Interestadual',
                         'N',
                         'Internacional',
                         'G',
                         'Gratuita',
                         'T',
                         'Turistica',
                         'Nao cadastrado') Classificacao,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       d.Vlr_Total) *
                                
                                Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                       0,
                                       0,
                                       d. Qtd_Passag_Trans)),
                            0)) Receita_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       Decode(Nvl(d.Qtd_Passag_Emb, 0),
                                              0,
                                              1,
                                              d.Qtd_Passag_Emb) * d.Vlr_Taxa_Emb)),
                            0)) Vlr_Txemb_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                              0,
                                              1,
                                              d. Qtd_Passag_Trans) *
                                       d.Vlr_Pedagio)),
                            0)) Vlr_Pedagio_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       Decode(Nvl(o.Flg_Somarseguro, 'N'),
                                              'S',
                                              Nvl(d.Qtd_Passag_Segurado, 0) *
                                              d.Vlr_Seguro),
                                       0)),
                            0)) Vlr_Seguroi_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       Decode(Nvl(o.Flg_Somarseguro, 'N'),
                                              'N',
                                              Nvl(d.Qtd_Passag_Segurado, 0) *
                                              d.Vlr_Seguro),
                                       0)),
                            0)) Vlr_Seguroni_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       d.Vlr_Outros,
                                       0)),
                            0)) Vlr_Outros_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       d.Vlr_Receb,
                                       0)),
                            0)) Vlr_Total_Alp,
                 Decode(Pp.Codtppagto,
                        '',
                        0,
                        Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                       Pp.Codtppagto,
                                       d.Vlr_Tmr,
                                       0) *
                                
                                Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                       0,
                                       1,
                                       d. Qtd_Passag_Trans)),
                            0)) Vlr_Tmr_Alp,
                 0 Receita,
                 0 Vlr_Txemb,
                 0 Vlr_Pedagio,
                 0 Vlr_Seguroi,
                 0 Vlr_Seguroni,
                 0 Vlr_Outros,
                 0 Vlr_Total,
                 0 Vlr_Tmr
           From t_Arr_Detalhe_Guia      d,
                 Bgm_Cadlinhas           l,
                 t_Trf_Param_Tppagto     p,
                 t_Trf_Orgaoconcedente   o,
                 t_Arr_Guia              g,
                 t_Trf_Paramempre        a,
                 t_Trf_Agencia           c,
                 t_Arr_Local_Arrecadacao r,
                 t_Arr_Paramtppagto      Pp
          Where d.Cod_Tipopagtarifa = p.Cod_Tipopagto
            And d.Cod_Seq_Guia = g.Cod_Seq_Guia
            And d.Codintlinha = l.Codintlinha
            And l.Codigoorgconc = o.Cod_Orgconc(+)
            And a.Cod_Empresa = g.Cod_Empresa
            And a.Codigofl = g.Codigofl
            And (d.Codlanca Is Null Or d.codlanca = 0)
            And Pp.Codigoempresa(+) = a.Cod_Empresa
            And Pp.Codigofl(+) = a.Codigofl
            And d.Cod_Tipopagtarifa <> 'X'
            And Trunc(g.Dat_Prest_Contas) Between
                To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtIni */
                And To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtFin */
            And c.Ag_Ativa = 'S'
            And ((g.Cod_Empresa = 004 And g.Codigofl = 001))
            And ((c.Cod_Seq_Agencia = 00066))
            And r.Cod_Local_Arr = g.Cod_Local_Arr
            And c.Cod_Seq_Agencia = r.Cod_Seq_Agencia
          Group By g.Cod_Empresa,
                    g.Codigofl,
                    c.Codigofl_Intctb,
                    Pp.Codtppagto,
                    c.Nom_Agencia,
                    Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V'),
                    Nvl(l.Codigotplinha, 9),
                    Nvl(l.Flg_Munic_Interest, 'Z'),
                    c.Cod_Seq_Agencia,
                    c.Cod_Agencia,
                    r.Cod_Local_Arr,
                    l.Codigotplinha,
                    l.Flg_Munic_Interest,
                    a.Tppagto_Alp,
                    a.Fechasemreceitaguia,
                    a.Flg_Recguiaagencia,
                    Trunc(g.Dat_Prest_Contas),
                    Cod_Tipopagtarifa
         Union All
         Select c.Cod_Agencia,
                c.Nom_Agencia,
                a.Fechasemreceitaguia,
                a.Flg_Recguiaagencia,
                c.Cod_Seq_Agencia,
                r.Cod_Local_Arr,
                Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V') Tpguia,
                g.Cod_Empresa,
                g.Codigofl,
                c.Codigofl_Intctb Filint,
                Nvl(l.Codigotplinha, 9) Tipolinha,
                Cod_Tipopagtarifa,
                Trunc(g.Dat_Prest_Contas) Data,
                Nvl(l.Flg_Munic_Interest, 'Z') Classlinha,
                a.Tppagto_Alp,
                Decode(Nvl(l.Codigotplinha, 9),
                        0,
                        'Rodoviaria',
                        1,
                        'Urbana',
                        2,
                        'Fretamento',
                        3,
                        'Suburbana',
                        'Nao cadastrado') Tplinha,
                Decode(Nvl(l.Flg_Munic_Interest, 'Z'),
                        'M',
                        'Municipal',
                        'U',
                        'Intermunicipal'                        
                       ,
                        'I',
                        'Interestadual',
                        'N',
                        'Internacional',
                        'G',
                        'Gratuita',
                        'T',
                        'Turistica',
                        'Nao cadastrado') Classificacao,
                0 Receita_Alp,
                0 Vlr_Txemb_Alp,
                0 Vlr_Pedagio_Alp,
                0 Vlr_Seguroi_Alp,
                0 Vlr_Seguroni_Alp,
                0 Vlr_Outros_Alp,
                0 Vlr_Total_Alp,
                0 Vlr_Tmr_Alp,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               0,
                               d. Qtd_Passag_Trans) * d.Vlr_Total),
                    0) Receita,
                
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Emb, 0),
                               0,
                               1,
                               d.Qtd_Passag_Emb) * d.Vlr_Taxa_Emb),
                    0) Vlr_Txemb,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               1,
                               d. Qtd_Passag_Trans) * d.Vlr_Pedagio),
                    0) Vlr_Pedagio,
                
                Nvl(Sum(Decode(Nvl(o.Flg_Somarseguro, 'N'),
                               'S',
                               (Nvl(d.Qtd_Passag_Segurado, 0) * d.Vlr_Seguro),
                               0)),
                    0) Vlr_Seguroi,
                
                Nvl(Sum(Decode(Nvl(o.Flg_Somarseguro, 'N'),
                               'N',
                               (Nvl(d.Qtd_Passag_Segurado, 0) * d.Vlr_Seguro),
                               0)),
                    0) Vlr_Seguroni,
                Nvl(Sum(d.Vlr_Outros), 0) Vlr_Outros,
                Nvl(Sum(d.Vlr_Receb), 0) Vlr_Total,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               1,
                               d. Qtd_Passag_Trans) * d.Vlr_Tmr),
                    0) Vlr_Tmr
           From t_Arr_Detalhe_Guia      d,
                Bgm_Cadlinhas           l,
                t_Trf_Param_Tppagto     p,
                t_Trf_Orgaoconcedente   o,
                t_Arr_Guia              g,
                t_Trf_Paramempre        a,
                t_Trf_Agencia           c,
                t_Arr_Local_Arrecadacao r
          Where d.Cod_Tipopagtarifa = p.Cod_Tipopagto
            And d.Cod_Seq_Guia = g.Cod_Seq_Guia
            And d.Codintlinha = l.Codintlinha
            And l.Codigoorgconc = o.Cod_Orgconc(+)
            And a.Cod_Empresa = g.Cod_Empresa
            And a.Codigofl = g.Codigofl
            And (d.Codlanca Is Null Or d.codlanca = 0)
            And d.Cod_Tipopagtarifa <> 'X'
            And Trunc(g.Dat_Prest_Contas) Between
                To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtIni */
                And To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtFin */
            And c.Ag_Ativa = 'S'
            And ((g.Cod_Empresa = 004 And g.Codigofl = 001))
            And ((c.Cod_Seq_Agencia = 00066))
            And r.Cod_Local_Arr = g.Cod_Local_Arr
            And c.Cod_Seq_Agencia = r.Cod_Seq_Agencia
          Group By g.Cod_Empresa,
                   g.Codigofl,
                   c.Codigofl_Intctb,
                   c.Nom_Agencia,
                   Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V'),
                   Nvl(l.Codigotplinha, 9),
                   Nvl(l.Flg_Munic_Interest, 'Z'),
                   c.Cod_Seq_Agencia,
                   c.Cod_Agencia,
                   r.Cod_Local_Arr,
                   l.Codigotplinha,
                   l.Flg_Munic_Interest,
                   a.Tppagto_Alp,
                   a.Fechasemreceitaguia,
                   a.Flg_Recguiaagencia,
                   Trunc(g.Dat_Prest_Contas),
                   d.Qtd_Passag_Trans,
                   d.Vlr_Total,
                   Cod_Tipopagtarifa
         Union All
         Select c.Cod_Agencia,
                c.Nom_Agencia,
                a.Fechasemreceitaguia,
                a.Flg_Recguiaagencia,
                c.Cod_Seq_Agencia,
                r.Cod_Local_Arr,
                Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V') Tpguia,
                g.Cod_Empresa,
                g.Codigofl,
                c.Codigofl_Intctb Filint,
                Nvl(l.Codigotplinha, 9) Tipolinha,
                Decode(b.Cod_Nrbolto,
                       0,
                       Cod_Tipopagtarifa,                       
                       Fc_Ret_Tppagtocancel_IntegCtb('VDALMEIDA192.168.5.140' /*                            PID_ESTACAO */,
                           '' /* PIMPOPOST 
                           */,
                           '' /* PVENDAANT */,
                           '' /* 
                           PCANCELVENDAANT */,
                           Cod_Tipopagtarifa,
                           b.Cod_Nrbolto,
                           Trunc(g.Dat_Prest_Contas),
                           g.Cod_Empresa,
                           g.Codigofl)) Cod_Tipopagtarifa,
                Trunc(g.Dat_Prest_Contas) Data,
                Nvl(l.Flg_Munic_Interest, 'Z') Classlinha,
                Pp.Codtppagto Tppagto_Alp,
                Decode(Nvl(l.Codigotplinha, 9),
                        0,
                        'Rodoviaria',
                        1,
                        'Urbana',
                        2,
                        'Fretamento',
                        3,
                        'Suburbana',
                        'Nao cadastrado') Tplinha,
                Decode(Nvl(l.Flg_Munic_Interest, 'Z'),
                        'M',
                        'Municipal',
                        'U',
                        'Intermunicipal'                        
                       ,
                        'I',
                        'Interestadual',
                        'N',
                        'Internacional',
                        'G',
                        'Gratuita',
                        'T',
                        'Turistica',
                        'Nao cadastrado') Classificacao,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      d.Vlr_Total) *
                               
                               Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                      0,
                                      0,
                                      d. Qtd_Passag_Trans)),
                           0)) Receita_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      Decode(Nvl(d.Qtd_Passag_Emb, 0),
                                             0,
                                             1,
                                             d.Qtd_Passag_Emb) * d.Vlr_Taxa_Emb)),
                           0)) Vlr_Txemb_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                             0,
                                             1,
                                             d. Qtd_Passag_Trans) *
                                      d.Vlr_Pedagio)),
                           0)) Vlr_Pedagio_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      Decode(Nvl(o.Flg_Somarseguro, 'N'),
                                             'S',
                                             Nvl(d.Qtd_Passag_Segurado, 0) *
                                             d.Vlr_Seguro),
                                      0)),
                           0)) Vlr_Seguroi_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      Decode(Nvl(o.Flg_Somarseguro, 'N'),
                                             'N',
                                             Nvl(d.Qtd_Passag_Segurado, 0) *
                                             d.Vlr_Seguro),
                                      0)),
                           0)) Vlr_Seguroni_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      d.Vlr_Outros,
                                      0)),
                           0)) Vlr_Outros_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      d.Vlr_Receb,
                                      0)),
                           0)) Vlr_Total_Alp,
                Decode(Pp.Codtppagto,
                       '',
                       0,
                       Nvl(Sum(Decode(d.Cod_Tipopagtarifa,
                                      Pp.Codtppagto,
                                      d.Vlr_Tmr,
                                      0) *
                               
                               Decode(Nvl(d.Qtd_Passag_Trans, 0),
                                      0,
                                      1,
                                      d. Qtd_Passag_Trans)),
                           0)) Vlr_Tmr_Alp,
                0 Receita,
                0 Vlr_Txemb,
                0 Vlr_Pedagio,
                0 Vlr_Seguroi,
                0 Vlr_Seguroni,
                0 Vlr_Outros,
                0 Vlr_Total,
                0 Vlr_Tmr
           From t_Arr_Detalhe_Guia      d,
                Bgm_Cadlinhas           l,
                t_Trf_Param_Tppagto     p,
                t_Trf_Orgaoconcedente   o,
                t_Arr_Guia              g,
                t_Trf_Paramempre        a,
                t_Trf_Agencia           c,
                t_Arr_Local_Arrecadacao r,
                t_Arr_Paramtppagto      Pp,
                t_Arr_Detalhe_Guiabolto b
          Where d.Cod_Tipopagtarifa = p.Cod_Tipopagto
            And d.Cod_Seq_Guia = g.Cod_Seq_Guia
            And d.Codintlinha = l.Codintlinha
            And l.Codigoorgconc = o.Cod_Orgconc(+)
            And a.Cod_Empresa = g.Cod_Empresa
            And a.Codigofl = g.Codigofl
            And b.Cod_Seq_Guia = d.Cod_Seq_Guia
            And b.Cod_Int_Item = d.Cod_Int_Item
            And (d.Codlanca Is Null Or d.codlanca = 0)
            And Pp.Codigoempresa(+) = a.Cod_Empresa
            And Pp.Codigofl(+) = a.Codigofl
            And d.Cod_Tipopagtarifa = 'X'
            And Trunc(g.Dat_Prest_Contas) Between
                To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtIni */
                And To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /*                PDtFin */
            And c.Ag_Ativa = 'S'
            And ((g.Cod_Empresa = 004 And g.Codigofl = 001))
            And ((c.Cod_Seq_Agencia = 00066))
            And r.Cod_Local_Arr = g.Cod_Local_Arr
            And c.Cod_Seq_Agencia = r.Cod_Seq_Agencia
          Group By g.Cod_Empresa,
                   g.Codigofl,
                   c.Codigofl_Intctb,
                   Pp.Codtppagto,
                   c.Nom_Agencia,
                   r.Cod_Local_Arr,
                   Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V'),
                   Nvl(l.Codigotplinha, 9),
                   Nvl(l.Flg_Munic_Interest, 'Z'),
                   c.Cod_Seq_Agencia,
                   c.Cod_Agencia,
                   l.Codigotplinha,
                   l.Flg_Munic_Interest,
                   a.Tppagto_Alp,
                   a.Fechasemreceitaguia,
                   a.Flg_Recguiaagencia,
                   Trunc(g.Dat_Prest_Contas),
                   Cod_Tipopagtarifa,
                   b.Cod_Nrbolto
         Union All
         Select c.Cod_Agencia,
                c.Nom_Agencia,
                a.Fechasemreceitaguia,
                a.Flg_Recguiaagencia,
                c.Cod_Seq_Agencia,
                r.Cod_Local_Arr,
                Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V') Tpguia,
                g.Cod_Empresa,
                g.Codigofl,
                c.Codigofl_Intctb Filint,
                Nvl(l.Codigotplinha, 9) Tipolinha,
                Decode(b.Cod_Nrbolto,
                       0,
                       Cod_Tipopagtarifa,
                       
                       Fc_Ret_Tppagtocancel_IntegCtb('VDALMEIDA192.168.5.140' /*                           PID_ESTACAO */,
                           '' /* PIMPOPOST 
                           */,
                           '' /* PVENDAANT */,
                           '' /* 
                           PCANCELVENDAANT */,
                           Cod_Tipopagtarifa,
                           b.Cod_Nrbolto,
                           Trunc(g.Dat_Prest_Contas),
                           g.Cod_Empresa,
                           g.Codigofl)) Cod_Tipopagtarifa,
                Trunc(g.Dat_Prest_Contas) Data,
                Nvl(l.Flg_Munic_Interest, 'Z') Classlinha,
                a.Tppagto_Alp,
                Decode(Nvl(l.Codigotplinha, 9),
                        0,
                        'Rodoviaria',
                        1,
                        'Urbana',
                        2,
                        'Fretamento',
                        3,
                        'Suburbana',
                        'Nao cadastrado') Tplinha,
                Decode(Nvl(l.Flg_Munic_Interest, 'Z'),
                        'M',
                        'Municipal',
                        'U',
                        'Intermunicipal'
                        
                       ,
                        'I',
                        'Interestadual',
                        'N',
                        'Internacional',
                        'G',
                        'Gratuita',
                        'T',
                        'Turistica',
                        'Nao cadastrado') Classificacao,
                0 Receita_Alp,
                0 Vlr_Txemb_Alp,
                0 Vlr_Pedagio_Alp,
                0 Vlr_Seguroi_Alp,
                0 Vlr_Seguroni_Alp,
                0 Vlr_Outros_Alp,
                0 Vlr_Total_Alp,
                0 Vlr_Tmr_Alp,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               0,
                               d. Qtd_Passag_Trans) * d.Vlr_Total),
                    0) Receita,
                
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Emb, 0),
                               0,
                               1,
                               d.Qtd_Passag_Emb) * d.Vlr_Taxa_Emb),
                    0) Vlr_Txemb,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               1,
                               d. Qtd_Passag_Trans) * d.Vlr_Pedagio),
                    0) Vlr_Pedagio,
                
                Nvl(Sum(Decode(Nvl(o.Flg_Somarseguro, 'N'),
                               'S',
                               (Nvl(d.Qtd_Passag_Segurado, 0) * d.Vlr_Seguro),
                               0)),
                    0) Vlr_Seguroi,
                
                Nvl(Sum(Decode(Nvl(o.Flg_Somarseguro, 'N'),
                               'N',
                               (Nvl(d.Qtd_Passag_Segurado, 0) * d.Vlr_Seguro),
                               0)),
                    0) Vlr_Seguroni,
                Nvl(Sum(d.Vlr_Outros), 0) Vlr_Outros,
                Nvl(Sum(d.Vlr_Receb), 0) Vlr_Total,
                Nvl(Sum(Decode(Nvl(d.Qtd_Passag_Trans, 0),
                               0,
                               1,
                               d. Qtd_Passag_Trans) * d.Vlr_Tmr),
                    0) Vlr_Tmr
           From t_Arr_Detalhe_Guia      d,
                Bgm_Cadlinhas           l,
                t_Trf_Param_Tppagto     p,
                t_Trf_Orgaoconcedente   o,
                t_Arr_Guia              g,
                t_Trf_Paramempre        a,
                t_Trf_Agencia           c,
                t_Arr_Local_Arrecadacao r,
                t_Arr_Detalhe_Guiabolto b
          Where d.Cod_Tipopagtarifa = p.Cod_Tipopagto
            And d.Cod_Seq_Guia = g.Cod_Seq_Guia
            And d.Codintlinha = l.Codintlinha
            And l.Codigoorgconc = o.Cod_Orgconc(+)
            And b.Cod_Seq_Guia = d.Cod_Seq_Guia
            And b.Cod_Int_Item = d.Cod_Int_Item
            And a.Cod_Empresa = g.Cod_Empresa
            And a.Codigofl = g.Codigofl
            And (d.Codlanca Is Null Or d.codlanca = 0)
            And d.Cod_Tipopagtarifa = 'X'
            And Trunc(g.Dat_Prest_Contas) Between
                To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /* 
               PDtIni */
                And To_Date('13/05/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') /* 
               PDtFin */
            And c.Ag_Ativa = 'S'
            And ((g.Cod_Empresa = 004 And g.Codigofl = 001))
            And ((c.Cod_Seq_Agencia = 00066))
            And r.Cod_Local_Arr = g.Cod_Local_Arr
            And c.Cod_Seq_Agencia = r.Cod_Seq_Agencia
          Group By g.Cod_Empresa,
                   g.Codigofl,
                   c.Codigofl_Intctb,
                   c.Nom_Agencia,
                   r.Cod_Local_Arr,
                   Decode(g.Flg_Tipo_Guia, 'A', 'A', 'V'),
                   Nvl(l.Codigotplinha, 9),
                   Nvl(l.Flg_Munic_Interest, 'Z'),
                   c.Cod_Seq_Agencia,
                   c.Cod_Agencia,
                   l.Codigotplinha,
                   l.Flg_Munic_Interest,
                   a.Tppagto_Alp,
                   a.Fechasemreceitaguia,
                   a.Flg_Recguiaagencia,
                   Trunc(g.Dat_Prest_Contas),
                   d.Qtd_Passag_Trans,
                   d.Vlr_Total,
                   Cod_Tipopagtarifa,
                   b.Cod_Nrbolto)
 Group By Cod_Agencia,
          Nom_Agencia,
          Fechasemreceitaguia,
          Flg_Recguiaagencia,
          Cod_Seq_Agencia,
          Cod_Local_Arr,
          Tpguia,
          Cod_Empresa,
          Codigofl,
          Filint,
          Tipolinha,
          Data,
          Classlinha,
          Tppagto_Alp,
          Tplinha,
          Classificacao,
          Cod_Tipopagtarifa