----------------------------------------------------EOVG DUTRA------------------------------------------------
SELECT LEVE.EMPRESA, LEVE.TOTAL, LEVE.TITULO, LEVE.VENCIDA_5000, LEVE.PREVISAO_5000

FROM

((SELECT DISTINCT/*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'REVISAO LEVE' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_5000,
  0 PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (111)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 111                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT DISTINCT/*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'REVISAO LEVE' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_5000,
  COUNT(PREFIXOVEIC) PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (111)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 111                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) LEVE

UNION ALL

SELECT PESADA.EMPRESA, PESADA.TOTAL, PESADA.TITULO, PESADA.VENCIDA_30000, PESADA.PREVISAO_30000

FROM
((SELECT /*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'REVISAO PESADA' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_30000,
  0 PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (112)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 112                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'REVISAO PESADA' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_30000,
  COUNT(PREFIXOVEIC) PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (112)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 112                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -6638 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) PESADA

UNION ALL
SELECT OLEO.EMPRESA, OLEO.TOTAL, OLEO.TITULO, OLEO.VENCIDA_15000, OLEO.PREVISAO_15000
FROM

((SELECT /*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'TROCA DE OLEO' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_15000,
  0 PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (114)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 114                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '001/001 EMPRESA DE ONIBUS VILA GALVAO' EMPRESA,
  'TROCA DE OLEO' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_15000,
  COUNT(PREFIXOVEIC) PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (114)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 114                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) OLEO 

UNION ALL
---------------------------------------------------EOVG LAVRAS-----------------------------------------------
SELECT LEVE.EMPRESA, LEVE.TOTAL, LEVE.TITULO, LEVE.VENCIDA_5000, LEVE.PREVISAO_5000

FROM

((SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'REVISAO LEVE' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_5000,
  0 PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (506,507)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (506,507)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'REVISAO LEVE' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_5000,
  COUNT(PREFIXOVEIC) PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (506,507)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (506,507)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) LEVE

UNION ALL

SELECT PESADA.EMPRESA, PESADA.TOTAL, PESADA.TITULO, PESADA.VENCIDA_30000, PESADA.PREVISAO_30000

FROM
((SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'REVISAO PESADA' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_30000,
  0 PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (511)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (511)                 AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'REVISAO PESADA' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_30000,
  COUNT(PREFIXOVEIC) PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (511)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (511)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -6422 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) PESADA

UNION ALL
SELECT OLEO.EMPRESA, OLEO.TOTAL, OLEO.TITULO, OLEO.VENCIDA_15000, OLEO.PREVISAO_15000
FROM

((SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'TROCA DE OLEO' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_15000,
  0 PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (508)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (508)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '001/002 EMPRESA DE ONIBUS VILA GALVAO (LAVRAS)' EMPRESA,
  'TROCA DE OLEO' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_15000,
  COUNT(PREFIXOVEIC) PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 1 AND 

A.CODIGOFL = 2 AND A.CODGRPREV = 150 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 1 AND A.CODIGOFL = 2 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 150 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (508)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 1 AND C.CODIGOFL = 2   AND
    D.CODIGOPLANREV IN (508)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 1 AND CODIGOFL = 2                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) OLEO 

UNION ALL
---------------------------------------VIACAO ARUJA------------------------------------------
--UNION ALL

SELECT LEVE.EMPRESA, LEVE.TOTAL, LEVE.TITULO, LEVE.VENCIDA_5000, LEVE.PREVISAO_5000

FROM

((SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'REVISAO LEVE' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_5000,
  0 PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (177)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (177)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'REVISAO LEVE' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_5000,
  COUNT(PREFIXOVEIC) PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (177)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (177)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -4000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) LEVE

UNION ALL

SELECT PESADA.EMPRESA, PESADA.TOTAL, PESADA.TITULO, PESADA.VENCIDA_30000, PESADA.PREVISAO_30000

FROM
((SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'REVISAO PESADA' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_30000,
  0 PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (172)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (172)                 AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'REVISAO PESADA' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_30000,
  COUNT(PREFIXOVEIC) PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (172)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (172)               AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5310 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) PESADA

UNION ALL
SELECT OLEO.EMPRESA, OLEO.TOTAL, OLEO.TITULO, OLEO.VENCIDA_15000, OLEO.PREVISAO_15000
FROM

((SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'TROCA DE OLEO' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_15000,
  0 PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (169)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (169)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '006/001 VIACAO ARUJA' EMPRESA,
  'TROCA DE OLEO' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_15000,
  COUNT(PREFIXOVEIC) PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND A.CODGRPREV IN (600,8,5) AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 6 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV IN (600,8,5) 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (169)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 6 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV IN (169)                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 6 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -4000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) OLEO 

UNION ALL
----------------------------------------------------VUG  DUTRA------------------------------------------------
SELECT LEVE.EMPRESA, LEVE.TOTAL, LEVE.TITULO, LEVE.VENCIDA_5000, LEVE.PREVISAO_5000

FROM

((SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'REVISAO LEVE' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_5000,
  0 PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (111)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 111                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'REVISAO LEVE' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_5000,
  COUNT(PREFIXOVEIC) PREVISAO_5000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (111)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 111                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) LEVE

UNION ALL

SELECT PESADA.EMPRESA, PESADA.TOTAL, PESADA.TITULO, PESADA.VENCIDA_30000, PESADA.PREVISAO_30000

FROM
((SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'REVISAO PESADA' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_30000,
  0 PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (112)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 112                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'REVISAO PESADA' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_30000,
  COUNT(PREFIXOVEIC) PREVISAO_30000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (112)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 112                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -6165 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) PESADA

UNION ALL
SELECT OLEO.EMPRESA, OLEO.TOTAL, OLEO.TITULO, OLEO.VENCIDA_15000, OLEO.PREVISAO_15000
FROM

((SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'TROCA DE OLEO' TITULO,
  0 TOTAL,
  COUNT(PREFIXOVEIC) VENCIDA_15000,
  0 PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (114)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 114                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > 0)
GROUP by   VEIC.TOTAL
)

UNION ALL

(SELECT /*+ RULE */ 
  '026/001 VIACAO URBANA GUARULHOS S/A' EMPRESA,
  'TROCA DE OLEO' TITULO,
  VEIC.TOTAL,
  0 VENCIDA_15000,
  COUNT(PREFIXOVEIC) PREVISAO_15000
/*  
  PREFIXOVEIC, 
  NVL(KMATUAL,0) AS KMATUAL,      
  VALORKMREVISAO,
  VEIC.MEDIAKMDIAVEIC, 
  OS.DATA,
  OS.KMEXCESSO,
  1500 Tolerancia_P5000
*/
FROM 
  ( 
   SELECT 
     V.TOTAL,   
     CODIGOVEIC, 
     PREFIXOVEIC, 
     PLACAATUALVEIC, 
     DTINICIOUTILVEIC, 
     MEDIAKMDIAVEIC, 
     KMATUAL, 
     V.CODGRPREV, 
     V.DESCRICAOTPFROTA,
     TIPOHORDIAKMPLANREV, 
     FORMADECONTROLEPLANREV, 
     P.CODIGOPLANREV, 
     P.DESCRICAOPLANREV,
     F.VALORKMREVISAO, 
     F.SEQKMREVISAO     
   FROM 
     ( 
      SELECT 
       TL_V.TOTAL,
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV, 
       NVL(MAX(B.KMACUMULADOVELOC),
       MAX(A.KMINICIALVEIC)) AS KMATUAL 
      FROM
       (SELECT COUNT(A.CODIGOVEIC) TOTAL FROM FRT_CADVEICULOS A WHERE A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND A.CODGRPREV = 7 AND A.CONDICAOVEIC = 'A')TL_V, 
       FRT_CADVEICULOS A, 
       BGM_VELOCIMETRO B,
       FRT_TIPODEFROTA F 
      WHERE 
       A.CODIGOEMPRESA = 26 AND A.CODIGOFL = 1 AND
       A.CODIGOTPFROTA = F.CODIGOTPFROTA       AND
       A.CODIGOVEIC    = B.CODIGOVEIC(+)       AND 
--       A.ACEITAMOVVENDAVEIC = 'S'              AND 
--       A.UTILIZAHORIMETROVEIC = 'N' AND 
       ((B.DATAVELOC    <= SYSDATE )  OR (B.DATAVELOC IS NULL))  AND 
       A.CONDICAOVEIC = 'A' AND
       A.CODGRPREV = 7 
     GROUP BY
       TL_V.TOTAL, 
       A.CODIGOVEIC, 
       A.PREFIXOVEIC, 
       A.PLACAATUALVEIC, 
       A.DTINICIOUTILVEIC, 
       F.DESCRICAOTPFROTA,
       A.MEDIAKMDIAVEIC, 
       A.CODGRPREV) V, 
     MAN_PLANODEREVISAO P, 
     MAN_KMREVISAO      F 
   WHERE 
     P.CODIGOPLANREV IN (114)    AND
     V.CODGRPREV     = F.CODGRPREV AND 
     F.CODIGOPLANREV = P.CODIGOPLANREV 
  ) VEIC, 
  (SELECT 
     C.CODIGOVEIC,  
     D.CODIGOPLANREV, 
     fcman_kmexcessoplano(C.CODIGOVEIC,SYSDATE,D.CODIGOPLANREV,1) AS KMEXCESSO,
     MAX(C.CODINTOS) CODINTOS,
     MAX(C.DATAFECHAMENTOOS)      AS DATA, 
     MAX(H.QTDEEXECUCAOPLANO)     AS QTDEEXECUCAOPLANO 
   FROM 
    MAN_OSREALIZADO D, 
    MAN_OS          C, 
    MAN_QTDEEXECUCOESPLANO  H, 
    MAN_KMREVISAO           W 
   WHERE 
    C.CODINTOS          = D.CODINTOS          AND  
    H.QTDEEXECUCAOPLANO = W.SEQKMREVISAO  (+) AND 
    H.CODIGOPLANREV     = W.CODIGOPLANREV (+) AND 
    D.CODIGOPLANREV     = H.CODIGOPLANREV     AND 
    C.CODIGOVEIC        = H.CODIGOVEIC        AND 
    C.CODIGOEMPRESA = 26 AND C.CODIGOFL = 1   AND
    D.CODIGOPLANREV = 114                     AND
    C.CODIGOVEIC IN ( SELECT 
                       CODIGOVEIC 
                      FROM 
                       FRT_CADVEICULOS 
                      WHERE 
                       CONDICAOVEIC = 'A' AND
                       CODIGOEMPRESA = 26 AND CODIGOFL = 1                        
  ) 
   GROUP BY 
    C.CODIGOVEIC, 
    D.CODIGOPLANREV
  ) OS
WHERE
  VEIC.CODIGOVEIC     = OS.CODIGOVEIC     (+)   AND 
  VEIC.CODIGOPLANREV  = OS.CODIGOPLANREV  (+)   AND
--  VEIC.SEQKMREVISAO   = DECODE(VEIC.FORMADECONTROLEPLANREV,'M',1,NVL(OS.QTDEEXECUCAOPLANO,0)+1) AND
  (OS.KMEXCESSO > -5000 and OS.KMEXCESSO < 0)
GROUP by   VEIC.TOTAL
)) OLEO  
 
 
 
 
 
 
 
