SELECT 
  A.CODIGOEMPRESA, 
  A.CODIGOFL, 
  A.CODIGOGA, 
  D.CODIGOVEIC, 
  D.PREFIXOVEIC, 
  W.DESCRICAOMODCHASSI, 
  A.KMEXECUCAOOS, 
  C.DATAINICIOEXECSERVOSREA, 
  A.CODINTOS, 
  A.NUMEROOS, 
  A.HORAABERTURAOS, 
  A.CONDICAOOS, 
  A.CODORIGOS, 
  B.CODORIGOS    CODORIGDEF, 
  C.CODIGOGRPSERVI, 
  Q.DESCRICAOGRPSERVI, 
  F.CODIGOCADSERVI, 
  F.DESCRICAOCADSERVI, 
  C.DESCRCOMPLOSREA, 
  C.CODIGOPLANREV, 
  E.CODIGOTPOPERSERVI, 
  E.DESCRICAOTPOPERSERVI, 
  D.CODIGOEMPRESA              
CODIGOEMPRESAVEIC, 
  D.CODIGOFL                   
CODIGOFLVEIC, 
  D.CODIGOGA                   
CODIGOGAVEIC, 
  J.CODFUNC, 
  J.CHAPAFUNC, 
  DECODE
(R.TRABCHAPAPAR,'S',J.CHAPAFUNC,J.CODFUNC) 
COD_MOTORISTA, 
  J.NOMEFUNC                   
NOME_MOTORISTA, 
  C.USUARIO                    USUARIO, 
  O.CODIGOLINHA, 
  O.NOMELINHA, 
  C.VLRMOBRASERVOSREA          
M_EXTERNA, 
  C.VLRPECASSERVOSREA          
P_EXTERNA, 
  A.ATUALI_INICIAL, 
  PL.TIPOHORDIAKMPLANREV, 
  C.SEQSERVOSPREV, 
  C.SEQSERVOSREAL, 
  A.SERVICOINTEXTOS, 
  A.OBSERVACAOOS, 
  CONT.CONTADOR, 
  DECODE
(R.TRABCHAPAPAR,'S',I.CHAPAFUNC,I.CODFUNC) CHAPA, 
  I.NOMEFUNC                   NOME, 
  H.VALORMOOSFUNC              
M_INTERNA, 
  H.HORAFINALOSFUNC, 
  H.HORAINICIALOSFUNC, 
  (H.TOTHORASOSFUNC * 60) + 
       ((((H.TOTHORASOSFUNC * 60) 
+ 
       DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                '00', 
                0, 
                ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
       TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) - 
       (TRUNC
(((H.TOTHORASOSFUNC * 60) + 
               DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                       '00', 
                       0, 
                       ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
               TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) / 
3600) * 3600)) 
       - 
       TRUNC
((((H.TOTHORASOSFUNC * 60) + 
             DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                      '00', 
                      0, 
                      ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
             TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) - 
             (TRUNC
(((H.TOTHORASOSFUNC * 60) + 
                     DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                             '00', 
                             0, 
                             ABS
((TO_NUMBER(TO_CHAR
(H.HORAINICIALOSFUNC, 
                                                    
'SS')) - 60))) + 
                     TO_NUMBER
(TO_CHAR(H.HORAFINALOSFUNC, 
'SS'))) / 3600) * 3600)) / 60) * 60) AS 
TOTHORASOSFUNC 
 ,B.CODIGOPLANREV 
 ,B.CODIGOGRPDEFEITO 
 ,B.CODIGODEFEITO 
 ,C.CODINTNF 
FROM 
  MAN_OS                      A, 
  MAN_OSPREVISTO              B, 
  MAN_OSREALIZADO             C, 
  FRT_CADVEICULOS             D, 
  MAN_TIPOOPERACAOSERVI       
E, 
  MAN_CADASTRODESERVICOS      
F, 
  FLP_FUNCIONARIOS            J, 
  FRT_MODCHASSI               W, 
  BGM_CADLINHAS               O, 
  MAN_GRUPODESERVICO          Q 
  ,MAN_OSFUNCIONARIOS       H, 
  FLP_FUNCIONARIOS          I, 
  FLP_PARAMETROS S, 
  ( 
    SELECT DISTINCT 
      A.CODINTOS, 
      H.CODINTFUNC, 
      H.HORAFINALOSFUNC, 
      H.HORAINICIALOSFUNC, 
      COUNT(*) CONTADOR 
    FROM 
      MAN_OS             A, 
      MAN_OSPREVISTO     B, 
      MAN_OSREALIZADO    C, 
      FRT_CADVEICULOS    D, 
      MAN_OSFUNCIONARIOS H, 
      FLP_FUNCIONARIOS   J, 
      FLP_PARAMETROS     R 
    WHERE 
      A.CODINTOS                = 
B.CODINTOS       AND 
      B.CODINTOS                = 
C.CODINTOS       AND 
      B.SEQSERVOSPREV           = 
C.SEQSERVOSPREV  AND 
      C.CODINTOS                = 
H.CODINTOS       AND 
      C.SEQSERVOSPREV           = 
H.SEQSERVOSPREV  AND 
      C.SEQSERVOSREAL           = 
H.SEQSERVOSREAL  AND 
      A.CODIGOVEIC              = 
D.CODIGOVEIC     AND 
      H.CODINTFUNC              = 
J.CODINTFUNC(+)  AND 
      J.CODIGOEMPRESA           = 
R.CODIGOEMPRESA(+)  AND 
      A.CONDICAOOS              IN 
('FP','FC','FE') AND 
      
D.APRESENTARELATORIOVEIC  = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 
    GROUP BY 
      A.CODINTOS, 
      H.CODINTFUNC, 
      H.DATAEXECOSFUNC, 
      H.HORAFINALOSFUNC, 
      H.HORAINICIALOSFUNC 
  ) CONT 
  ,FLP_PARAMETROS     R 
  ,MAN_PLANODEREVISAO PL 
WHERE 
  A.CODINTOS           = 
CONT.CODINTOS          AND 
  I.CODINTFUNC         = 
CONT.CODINTFUNC        AND 
  H.HORAFINALOSFUNC    = 
CONT.HORAFINALOSFUNC   AND 
  H.HORAINICIALOSFUNC  = 
CONT.HORAINICIALOSFUNC AND 
  C.CODINTOS           = 
H.CODINTOS(+)          AND 
  C.SEQSERVOSREAL      = 
H.SEQSERVOSREAL(+)     AND 
  C.SEQSERVOSPREV      = 
H.SEQSERVOSPREV(+)     AND 
  H.CODINTFUNC         = 
I.CODINTFUNC(+)        AND 
  A.SERVICOINTEXTOS    = 'I'            
      AND 
  I.CODIGOEMPRESA      = 
S.CODIGOEMPRESA(+)     AND 
  A.CODINTOS           = 
B.CODINTOS             AND 
  B.SEQSERVOSPREV      = 
C.SEQSERVOSPREV        AND 
  B.CODINTOS           = 
C.CODINTOS             AND 
  A.CODIGOVEIC         = 
D.CODIGOVEIC           AND 
  C.CODIGOTPOPERSERVI  = 
E.CODIGOTPOPERSERVI(+) AND 
  D.CODIGOMODCHASSI    = 
W.CODIGOMODCHASSI(+)   AND 
  C.CODIGOGRPSERVI     = 
F.CODIGOGRPSERVI       AND 
  C.CODIGOCADSERVI     = 
F.CODIGOCADSERVI       AND 
  A.CODINTFUNC         = 
J.CODINTFUNC(+)        AND 
  A.CODINTLINHA        = 
O.CODINTLINHA(+)       AND 
  C.CODIGOGRPSERVI     = 
Q.CODIGOGRPSERVI       AND 
  J.CODIGOEMPRESA      = 
R.CODIGOEMPRESA(+)     AND 
  C.CODIGOPLANREV      = 
PL.CODIGOPLANREV(+)    AND 
  A.CONDICAOOS         IN 
('FP','FC','FE')       AND 
  D.APRESENTARELATORIOVEIC = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 
UNION 
SELECT 
  A.CODIGOEMPRESA, 
  A.CODIGOFL, 
  A.CODIGOGA, 
  D.CODIGOVEIC, 
  D.PREFIXOVEIC, 
  W.DESCRICAOMODCHASSI, 
  A.KMEXECUCAOOS, 
  C.DATAINICIOEXECSERVOSREA, 
  A.CODINTOS, 
  A.NUMEROOS, 
  A.HORAABERTURAOS, 
  A.CONDICAOOS, 
  A.CODORIGOS, 
  B.CODORIGOS    CODORIGDEF, 
  C.CODIGOGRPSERVI, 
  Q.DESCRICAOGRPSERVI, 
  F.CODIGOCADSERVI, 
  F.DESCRICAOCADSERVI, 
  C.DESCRCOMPLOSREA, 
  C.CODIGOPLANREV, 
  E.CODIGOTPOPERSERVI, 
  E.DESCRICAOTPOPERSERVI, 
  D.CODIGOEMPRESA              
CODIGOEMPRESAVEIC, 
  D.CODIGOFL                   
CODIGOFLVEIC, 
  D.CODIGOGA                   
CODIGOGAVEIC, 
  J.CODFUNC, 
  J.CHAPAFUNC, 
  DECODE
(R.TRABCHAPAPAR,'S',J.CHAPAFUNC,J.CODFUNC) 
COD_MOTORISTA, 
  J.NOMEFUNC                   
NOME_MOTORISTA, 
  C.USUARIO                    USUARIO, 
  O.CODIGOLINHA, 
  O.NOMELINHA, 
  C.VLRMOBRASERVOSREA          
M_EXTERNA, 
  C.VLRPECASSERVOSREA          
P_EXTERNA, 
  A.ATUALI_INICIAL, 
  PL.TIPOHORDIAKMPLANREV, 
  C.SEQSERVOSPREV, 
  C.SEQSERVOSREAL, 
  A.SERVICOINTEXTOS, 
  A.OBSERVACAOOS, 
  1 CONTADOR, 
  ''  CHAPA, 
  '' NOME, 
  0 M_INTERNA, 
  TO_DATE
('31/12/1899','DD/MM/YYYY') 
HORAFINALOSFUNC, 
  TO_DATE
('31/12/1899','DD/MM/YYYY') 
HORAINICIALOSFUNC, 
  0 TOTHORASOSFUNC 
 ,B.CODIGOPLANREV 
 ,B.CODIGOGRPDEFEITO 
 ,B.CODIGODEFEITO 
 ,C.CODINTNF 
FROM 
  MAN_OS                      A, 
  MAN_OSPREVISTO              B, 
  MAN_OSREALIZADO             C, 
  FRT_CADVEICULOS             D, 
  MAN_TIPOOPERACAOSERVI       
E, 
  MAN_CADASTRODESERVICOS      
F, 
  FLP_FUNCIONARIOS            J, 
  FRT_MODCHASSI               W, 
  BGM_CADLINHAS               O, 
  MAN_GRUPODESERVICO          Q 
  ,FLP_PARAMETROS     R 
  ,MAN_PLANODEREVISAO PL 
WHERE 
  A.SERVICOINTEXTOS    = 'E'           
       AND 
  A.CODINTOS           = 
B.CODINTOS             AND 
  B.SEQSERVOSPREV      = 
C.SEQSERVOSPREV        AND 
  B.CODINTOS           = 
C.CODINTOS             AND 
  A.CODIGOVEIC         = 
D.CODIGOVEIC           AND 
  C.CODIGOTPOPERSERVI  = 
E.CODIGOTPOPERSERVI(+) AND 
  D.CODIGOMODCHASSI    = 
W.CODIGOMODCHASSI(+)   AND 
  C.CODIGOGRPSERVI     = 
F.CODIGOGRPSERVI       AND 
  C.CODIGOCADSERVI     = 
F.CODIGOCADSERVI       AND 
  A.CODINTFUNC         = 
J.CODINTFUNC(+)        AND 
  A.CODINTLINHA        = 
O.CODINTLINHA(+)       AND 
  C.CODIGOGRPSERVI     = 
Q.CODIGOGRPSERVI       AND 
  J.CODIGOEMPRESA      = 
R.CODIGOEMPRESA(+)     AND 
  C.CODIGOPLANREV      = 
PL.CODIGOPLANREV(+)    AND 
  A.CONDICAOOS         IN 
('FP','FC','FE')       AND 
  D.APRESENTARELATORIOVEIC = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 
UNION 
SELECT 
  A.CODIGOEMPRESA, 
  A.CODIGOFL, 
  A.CODIGOGA, 
  D.CODIGOVEIC, 
  D.PREFIXOVEIC, 
  W.DESCRICAOMODCHASSI, 
  A.KMEXECUCAOOS, 
  C.DATAINICIOEXECSERVOSREA, 
  A.CODINTOS, 
  A.NUMEROOS, 
  A.HORAABERTURAOS, 
  A.CONDICAOOS, 
  A.CODORIGOS, 
  B.CODORIGOS    CODORIGDEF, 
  C.CODIGOGRPSERVI, 
  Q.DESCRICAOGRPSERVI, 
  F.CODIGOCADSERVI, 
  F.DESCRICAOCADSERVI, 
  C.DESCRCOMPLOSREA, 
  C.CODIGOPLANREV, 
  E.CODIGOTPOPERSERVI, 
  E.DESCRICAOTPOPERSERVI, 
  D.CODIGOEMPRESA              
CODIGOEMPRESAVEIC, 
  D.CODIGOFL                   
CODIGOFLVEIC, 
  D.CODIGOGA                   
CODIGOGAVEIC, 
  J.CODPROAUT, 
  J.CODPROAUT, 
  DECODE
(R.TRABCHAPAPAR,'S',J.CODPROAUT,J.CODPROAUT) 
COD_MOTORISTA, 
  J.NOMEPROAUT                   
NOME_MOTORISTA, 
  C.USUARIO                    USUARIO, 
  O.CODIGOLINHA, 
  O.NOMELINHA, 
  C.VLRMOBRASERVOSREA          
M_EXTERNA, 
  C.VLRPECASSERVOSREA          
P_EXTERNA, 
  A.ATUALI_INICIAL, 
  PL.TIPOHORDIAKMPLANREV, 
  C.SEQSERVOSPREV, 
  C.SEQSERVOSREAL, 
  A.SERVICOINTEXTOS, 
  A.OBSERVACAOOS, 
  CONT.CONTADOR, 
  DECODE
(R.TRABCHAPAPAR,'S',I.CODPROAUT,I.CODPROAUT) CHAPA, 
  I.NOMEPROAUT                   
NOME, 
  H.VALORMOOSFUNC              
M_INTERNA, 
  H.HORAFINALOSFUNC, 
  H.HORAINICIALOSFUNC, 
  (H.TOTHORASOSFUNC * 60) + 
       ((((H.TOTHORASOSFUNC * 60) 
+ 
       DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                '00', 
                0, 
                ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
       TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) - 
       (TRUNC
(((H.TOTHORASOSFUNC * 60) + 
               DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                       '00', 
                       0, 
                       ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
               TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) / 
3600) * 3600)) 
       - 
       TRUNC
((((H.TOTHORASOSFUNC * 60) + 
             DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                      '00', 
                      0, 
                      ABS((TO_NUMBER
(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS')) - 
60))) + 
             TO_NUMBER(TO_CHAR
(H.HORAFINALOSFUNC, 'SS'))) - 
             (TRUNC
(((H.TOTHORASOSFUNC * 60) + 
                     DECODE(TO_CHAR
(H.HORAINICIALOSFUNC, 'SS'), 
                             '00', 
                             0, 
                             ABS
((TO_NUMBER(TO_CHAR
(H.HORAINICIALOSFUNC, 
                                                    
'SS')) - 60))) + 
                     TO_NUMBER
(TO_CHAR(H.HORAFINALOSFUNC, 
'SS'))) / 3600) * 3600)) / 60) * 60) AS 
TOTHORASOSFUNC 
 ,B.CODIGOPLANREV 
 ,B.CODIGOGRPDEFEITO 
 ,B.CODIGODEFEITO 
 ,C.CODINTNF 
FROM 
  MAN_OS                      A, 
  MAN_OSPREVISTO              B, 
  MAN_OSREALIZADO             C, 
  FRT_CADVEICULOS             D, 
  MAN_TIPOOPERACAOSERVI       
E, 
  MAN_CADASTRODESERVICOS      
F, 
  FLP_PROAUTONOMOS            J, 
  FRT_MODCHASSI               W, 
  BGM_CADLINHAS               O, 
  MAN_GRUPODESERVICO          Q 
  ,MAN_OSFUNCIONARIOS       H, 
  FLP_PROAUTONOMOS          I, 
  FLP_PARAMETROS S, 
  ( 
    SELECT DISTINCT 
      A.CODINTOS, 
      H.CODINTPROAUT, 
      H.HORAFINALOSFUNC, 
      H.HORAINICIALOSFUNC, 
      COUNT(*) CONTADOR 
    FROM 
      MAN_OS             A, 
      MAN_OSPREVISTO     B, 
      MAN_OSREALIZADO    C, 
      FRT_CADVEICULOS    D, 
      MAN_OSFUNCIONARIOS H, 
      FLP_PROAUTONOMOS   J, 
      FLP_PARAMETROS     R 
    WHERE 
      A.CODINTOS                = 
B.CODINTOS       AND 
      B.CODINTOS                = 
C.CODINTOS       AND 
      B.SEQSERVOSPREV           = 
C.SEQSERVOSPREV  AND 
      C.CODINTOS                = 
H.CODINTOS       AND 
      C.SEQSERVOSPREV           = 
H.SEQSERVOSPREV  AND 
      C.SEQSERVOSREAL           = 
H.SEQSERVOSREAL  AND 
      A.CODIGOVEIC              = 
D.CODIGOVEIC     AND 
      H.CODINTPROAUT              = 
J.CODINTPROAUT(+)  AND 
      J.CODIGOEMPRESA           = 
R.CODIGOEMPRESA(+)  AND 
      A.CONDICAOOS              IN 
('FP','FC','FE') AND 
      
D.APRESENTARELATORIOVEIC  = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 
    GROUP BY 
      A.CODINTOS, 
      H.CODINTPROAUT, 
      H.DATAEXECOSFUNC, 
      H.HORAFINALOSFUNC, 
      H.HORAINICIALOSFUNC 
  ) CONT 
  ,FLP_PARAMETROS     R 
  ,MAN_PLANODEREVISAO PL 
WHERE 
  A.CODINTOS           = 
CONT.CODINTOS          AND 
  I.CODINTPROAUT         = 
CONT.CODINTPROAUT        AND 
  H.HORAFINALOSFUNC    = 
CONT.HORAFINALOSFUNC   AND 
  H.HORAINICIALOSFUNC  = 
CONT.HORAINICIALOSFUNC AND 
  C.CODINTOS           = 
H.CODINTOS(+)          AND 
  C.SEQSERVOSREAL      = 
H.SEQSERVOSREAL(+)     AND 
  C.SEQSERVOSPREV      = 
H.SEQSERVOSPREV(+)     AND 
  H.CODINTPROAUT         = 
I.CODINTPROAUT(+)        AND 
  A.SERVICOINTEXTOS    = 'I'            
      AND 
  I.CODIGOEMPRESA      = 
S.CODIGOEMPRESA(+)     AND 
  A.CODINTOS           = 
B.CODINTOS             AND 
  B.SEQSERVOSPREV      = 
C.SEQSERVOSPREV        AND 
  B.CODINTOS           = 
C.CODINTOS             AND 
  A.CODIGOVEIC         = 
D.CODIGOVEIC           AND 
  C.CODIGOTPOPERSERVI  = 
E.CODIGOTPOPERSERVI(+) AND 
  D.CODIGOMODCHASSI    = 
W.CODIGOMODCHASSI(+)   AND 
  C.CODIGOGRPSERVI     = 
F.CODIGOGRPSERVI       AND 
  C.CODIGOCADSERVI     = 
F.CODIGOCADSERVI       AND 
  A.CODINTPROAUT         = 
J.CODINTPROAUT(+)        AND 
  A.CODINTLINHA        = 
O.CODINTLINHA(+)       AND 
  C.CODIGOGRPSERVI     = 
Q.CODIGOGRPSERVI       AND 
  J.CODIGOEMPRESA      = 
R.CODIGOEMPRESA(+)     AND 
  C.CODIGOPLANREV      = 
PL.CODIGOPLANREV(+)    AND 
  A.CONDICAOOS         IN 
('FP','FC','FE')       AND 
  D.APRESENTARELATORIOVEIC = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 
UNION 
SELECT 
  A.CODIGOEMPRESA, 
  A.CODIGOFL, 
  A.CODIGOGA, 
  D.CODIGOVEIC, 
  D.PREFIXOVEIC, 
  W.DESCRICAOMODCHASSI, 
  A.KMEXECUCAOOS, 
  C.DATAINICIOEXECSERVOSREA, 
  A.CODINTOS, 
  A.NUMEROOS, 
  A.HORAABERTURAOS, 
  A.CONDICAOOS, 
  A.CODORIGOS, 
  B.CODORIGOS    CODORIGDEF, 
  C.CODIGOGRPSERVI, 
  Q.DESCRICAOGRPSERVI, 
  F.CODIGOCADSERVI, 
  F.DESCRICAOCADSERVI, 
  C.DESCRCOMPLOSREA, 
  C.CODIGOPLANREV, 
  E.CODIGOTPOPERSERVI, 
  E.DESCRICAOTPOPERSERVI, 
  D.CODIGOEMPRESA              
CODIGOEMPRESAVEIC, 
  D.CODIGOFL                   
CODIGOFLVEIC, 
  D.CODIGOGA                   
CODIGOGAVEIC, 
  J.CODPROAUT, 
  J.CODPROAUT, 
  DECODE
(R.TRABCHAPAPAR,'S',J.CODPROAUT,J.CODPROAUT) 
COD_MOTORISTA, 
  J.NOMEPROAUT                   
NOME_MOTORISTA, 
  C.USUARIO                    USUARIO, 
  O.CODIGOLINHA, 
  O.NOMELINHA, 
  C.VLRMOBRASERVOSREA          
M_EXTERNA, 
  C.VLRPECASSERVOSREA          
P_EXTERNA, 
  A.ATUALI_INICIAL, 
  PL.TIPOHORDIAKMPLANREV, 
  C.SEQSERVOSPREV, 
  C.SEQSERVOSREAL, 
  A.SERVICOINTEXTOS, 
  A.OBSERVACAOOS, 
  1 CONTADOR, 
  ''  CHAPA, 
  '' NOME, 
  0 M_INTERNA, 
  TO_DATE
('31/12/1899','DD/MM/YYYY') 
HORAFINALOSFUNC, 
  TO_DATE
('31/12/1899','DD/MM/YYYY') 
HORAINICIALOSFUNC, 
  0 TOTHORASOSFUNC 
 ,B.CODIGOPLANREV 
 ,B.CODIGOGRPDEFEITO 
 ,B.CODIGODEFEITO 
 ,C.CODINTNF 
FROM 
  MAN_OS                      A, 
  MAN_OSPREVISTO              B, 
  MAN_OSREALIZADO             C, 
  FRT_CADVEICULOS             D, 
  MAN_TIPOOPERACAOSERVI       
E, 
  MAN_CADASTRODESERVICOS      
F, 
  FLP_PROAUTONOMOS            J, 
  FRT_MODCHASSI               W, 
  BGM_CADLINHAS               O, 
  MAN_GRUPODESERVICO          Q 
  ,FLP_PARAMETROS     R 
  ,MAN_PLANODEREVISAO PL 
WHERE 
  A.SERVICOINTEXTOS    = 'E'           
       AND 
  A.CODINTOS           = 
B.CODINTOS             AND 
  B.SEQSERVOSPREV      = 
C.SEQSERVOSPREV        AND 
  B.CODINTOS           = 
C.CODINTOS             AND 
  A.CODIGOVEIC         = 
D.CODIGOVEIC           AND 
  C.CODIGOTPOPERSERVI  = 
E.CODIGOTPOPERSERVI(+) AND 
  D.CODIGOMODCHASSI    = 
W.CODIGOMODCHASSI(+)   AND 
  C.CODIGOGRPSERVI     = 
F.CODIGOGRPSERVI       AND 
  C.CODIGOCADSERVI     = 
F.CODIGOCADSERVI       AND 
  A.CODINTPROAUT         = 
J.CODINTPROAUT(+)        AND 
  A.CODINTLINHA        = 
O.CODINTLINHA(+)       AND 
  C.CODIGOGRPSERVI     = 
Q.CODIGOGRPSERVI       AND 
  J.CODIGOEMPRESA      = 
R.CODIGOEMPRESA(+)     AND 
  C.CODIGOPLANREV      = 
PL.CODIGOPLANREV(+)    AND 
  A.CONDICAOOS         IN 
('FP','FC','FE')       AND 
  D.APRESENTARELATORIOVEIC = 
'S' 
 AND  ((A.CODIGOEMPRESA = 1 
AND A.CODIGOFL = 1)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 2)  OR 
(A.CODIGOEMPRESA = 1 AND 
A.CODIGOFL = 3) ) 
  AND 
C.DATAINICIOEXECSERVOSREA 
BETWEEN TO_DATE('01/05/2017 
00:00:00', 'DD/MM/YYYY 
HH24:MI:SS') /* P_DATAINI */  AND 
TO_DATE('18/05/2017 00:00:00', 
'DD/MM/YYYY HH24:MI:SS') /* 
P_DATAFIN */ 
  AND A.CODIGOVEIC IN (SELECT 
CODIGOVEIC FROM 
FRT_CADVEICULOS WHERE 
PREFIXOVEIC BETWEEN '0030441' 
/* P_VEICINI */  AND '0030441' /* 
P_VEICFIN */ ) 
 
 
  AND A.CODINTOS IN (SELECT 
CODINTOS FROM MAN_OS 
WHERE NUMEROOS BETWEEN 
316619 /* P_OSINI */  AND 316619 
/* P_OSFIN */ ) 